### ISSUE TITLE
[Buttons] Mismatch In Radius Between Color And White Background/Shadow Border

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5269] opened 2018-09-27 16:10 UTC
From the internal issue:

> Please fix the mismatch in radius between the color and the white background/shadow border

---

This is an internal issue. If you are a Googler, please visit [b/116782607](http://b/116782607) for more details.

---
#### Internal data
- Associated internal bug: [b/116782607](http://b/116782607)

**Comment by romoore** [comment] 2019-02-21 17:06
Closing as a duplicate of https://github.com/material-components/material-components-ios/issues/4419

**Closed by romoore** 2019-02-21 17:06 UTC
Labels: [Buttons], type:Bug
