### ISSUE TITLE
[MDCCollectionViewStyler] Custom border radius and color?

### ISSUE THREAD

**Issue by strangewiz** [material-components/material-components-ios#3050] opened 2018-03-06 18:45 UTC
e.g. override kCollectionViewCellDefaultBorderRadius and kCollectionViewCellDefaultBorderColor?

**Comment by samskiter** [comment] 2018-03-06 20:22
I think I'd rather see the collection view cells somehow aligned with the Card (unsure how this would work for the grouped style!)

**Comment by jverkoey** [comment] 2018-03-06 20:30
Hi @samskiter, it's possible you may be requesting a separate feature, can you file an issue outlining what you'd like to see?

**Comment by ianegordon** [comment] 2018-08-23 23:11
Closing as a duplicate of #4395.

Please re-open if that is not the case.

**Closed by ianegordon** 2018-08-23 23:11 UTC
Labels: Needs actionability review, [Collections], type:Bug
