### ISSUE TITLE
[TextFields] iOS docs have a typo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3974] opened 2018-05-10 02:51 UTC
on https://material.io/components/ios/catalog/textfields/

``` swift
textFieldControllerDefaultCharMax = MDCTextInputControllerUnderline(input: textFieldDefaultCharMax) // Hold on as a property
```

should be:

``` swift
textFieldControllerDefaultCharMax = MDCTextInputControllerUnderline(textInput: textFieldDefaultCharMax) // Hold on as a property
```

---

https://github.com/material-components/material-components-ios/issues/3334

**Comment by ianegordon** [comment] 2018-08-23 23:29
This is a dupe of #3334 which was closed in #4352.

**Closed by ianegordon** 2018-08-23 23:29 UTC
Labels: Needs actionability review, type:Bug
