### ISSUE TITLE
[Textfields] Support error / hint label overflow.

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1924] opened 2017-08-28 18:14 UTC
Currently hint / error text labels are not clipped by the bounds of the textfield.  This could lead to unexpected behavior if the label is long enough to go off the screen or collide with another visual element.

**Comment by willlarche** [comment] 2017-09-25 17:11
This is awaiting design.

**Comment by ravipxm** [comment] 2017-10-27 11:10
Any solution for this? I am getting this issue and it's really blocking my UI.

**Comment by willlarche** [comment] 2017-10-29 20:54
We are in the design approval process. There will be some multiple underline line text design but right now we aren't sure which.

**Comment by willlarche** [comment] 2017-11-13 18:22
The designs have been approved. There will be a maximum of 2 lines, not 1.

**Comment by ravipxm** [comment] 2017-11-14 03:44
@willlarche 

If you add the constraints between underlinelabel and underline then underlinelabel will grow and textfield too.

I am using this solution for now

**Comment by jverkoey** [comment] 2018-07-23 17:52
Duplicate of #4476

**Closed by jverkoey** 2018-07-23 17:52 UTC
Labels: Needs actionability review, [TextFields], type:Bug

**Comment by emilyvon** [comment] 2019-01-30 23:31
> @willlarche
> 
> If you add the constraints between underlinelabel and underline then underlinelabel will grow and textfield too.
> 
> I am using this solution for now

Would you please provide more details? Our error text is 6 lines long and this is really a blocker for us.
