### ISSUE TITLE
[List] List Themer does not respect colorScheme's backgroundColor

### ISSUE THREAD

**Issue by bryanoltman** [material-components/material-components-ios#7436] opened 2019-05-21 21:05 UTC
`MDCListColorThemer` does not respect the `backgroundColor` property of `MDCListScheme.colorScheme`.

## Reproduction steps

1. Open `catalog/MDCCatalog.xcworkspace`
1. In `MDCSelfSizingStereoCellExample.m`, update the `viewDidLoad` function to add a color scheme with a custom background color as follows:
```
  MDCSemanticColorScheme *scheme = [[MDCSemanticColorScheme alloc] init];
  scheme.backgroundColor = [UIColor redColor];
  self.listScheme.colorScheme = scheme;
```
1. Run the project and navigate to "List Items" -> "Self Sizing Stereo Cell Typical Use"

## Expected behavior

Every cell's `contentView.backgroundColor` is set to the color specified in the scheme.

## Actual behavior

Every cell's `contentView.backgroundColor` is unchanged (white).

## Platform

 - Device: iPhone7
 - OS: iOS11.0.1

---
#### Internal data
- Associated internal bug: [b/133255950](http://b/133255950)

**Comment by romoore** [comment] 2019-05-22 01:50
Duplicate of #7437

**Closed by romoore** 2019-05-22 01:50 UTC
Labels: [List], type:Bug
