### ISSUE TITLE
[FeatureHighlight] Content view is offset from AppBar after rotation to Landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3710] opened 2018-05-04 13:38 UTC
### Overview
The Feature Highlight "Demo" and "Shown Views" example will offset the content view incorrectly after rotating from Portrait to Landscape. This results in a black "box" below the App Bar.

### Reproduction steps
1. Open the catalog in Portrait
1. Open Feature Highlight &rarr; Start Demo
  a. Or Open Feature Highlight &rarr; Shown Views
1. Rotate to landscape

![simulator screen shot - iphone x - 2018-05-04 at 09 35 09](https://user-images.githubusercontent.com/1753199/39630896-bcc6e714-4f7e-11e8-8f77-4ff34370ccb2.png)

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3705

**Comment by rami-a** [comment] 2018-10-09 19:43
I tried to reproduce this issue and it looks like it was fixed inadvertently. Closing this out.

**Closed by rami-a** 2018-10-09 19:43 UTC
Labels: Internal, [Chips], app:Catalog, good first issue, type:Bug
