### ISSUE TITLE
[MDCTextField] Set background color

### ISSUE THREAD

**Issue by nastasiupta** [material-components/material-components-ios#9788] opened 2020-02-24 17:27 UTC
I try to set the background color for the input field and the color is outside the boundaries of MDCTextInputControllerOutlined 

## Reproduction steps
```
class FTextField: MDCTextField {
    
    let inputControllerOutlined = MDCTextInputControllerOutlined()
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        font = AppFonts.regular.font.withSize(14)
        textColor = Color.text.color
        inputControllerOutlined.textInput = self
        inputControllerOutlined.activeColor = Color.border(true).color
        inputControllerOutlined.normalColor = Color.border(false).color
        inputControllerOutlined.floatingPlaceholderActiveColor =  Color.border(true).color
        inputControllerOutlined.errorColor = Color.error.color
        clearButtonMode = .never
        backgroundColor = UIColor.white
    }
}
```

1. Place a custom FTextField in the storyboard and run 

## Expected behavior
the background view should be inside the boundaries of MDCTextInputControllerOutlined

## Actual behavior
<img width="379" alt="Screenshot 2020-02-24 at 19 26 35" src="https://user-images.githubusercontent.com/13376064/75175754-9a33e280-573b-11ea-9b19-6c06a3a19be5.png">

A clear and concise description of what actually happened. Include screenshots or gifs where possible.

## Platform (please complete the following information)

 - Device: iPhone Xs (simulator)
 - OS: iOS 13.2

**Comment by andrewoverton** [comment] 2020-02-24 21:29
Hi @nastasiupta, there is actually no way to set the background color of just the area within the outline. This is intended behavior, and it's true both when you're using MDCTextField with an MDCTextInputControllerOutlined and when you're using [MDCOutlinedTextField](https://github.com/material-components/material-components-ios/tree/develop/components/TextControls), which is the newer and preferred implementation for Material outlined text fields.

This is because there is a break in the outline when the text field has floating label text (the same thing as placeholder text in MDCTextField) and it would look bad to have the color stop at the border even when it's not there. Does that make sense?

**Comment by andrewoverton** [comment] 2020-02-24 21:30
I'm going to close this bug for now. Feel free to re-open if you'd like to discuss it further.

**Closed by andrewoverton** 2020-02-24 21:30 UTC
Labels: Needs actionability review

**Comment by smaljaar** [comment] 2020-03-13 09:43
> Hi @nastasiupta, there is actually no way to set the background color of just the area within the outline. This is intended behavior, and it's true both when you're using MDCTextField with an MDCTextInputControllerOutlined and when you're using [MDCOutlinedTextField](https://github.com/material-components/material-components-ios/tree/develop/components/TextControls), which is the newer and preferred implementation for Material outlined text fields.
> 
> This is because there is a break in the outline when the text field has floating label text (the same thing as placeholder text in MDCTextField) and it would look bad to have the color stop at the border even when it's not there. Does that make sense?

To me it does not make sense, I think. I'm trying to use this MDCOutlinedTextField as 'Outlined text field without labels'. In that case there is no floating label, and I just want a placeholder text. In addition I want another color of the background. To me it is very unclear and unintuitive that this is mentioned nowhere. Instead the API suggests you can use the ColorScheme, which has a background color property and a surface color, which both do nothing if they are applied.

**Comment by andrewoverton** [comment] 2020-03-13 17:16
Oh, I see. You're not using label text. Have you considered just using a UITextField and doing something like this?
```
textField.layer.borderColor = UIColor.blackColor.CGColor;
textField.layer.borderWidth = 1;
textField.layer.cornerRadius = 5;
textField.backgroundColor = UIColor.lightGrayColor;
```

**Comment by smaljaar** [comment] 2020-04-01 12:45
> Oh, I see. You're not using label text. Have you considered just using a UITextField and doing something like this?
> 
> ```
> textField.layer.borderColor = UIColor.blackColor.CGColor;
> textField.layer.borderWidth = 1;
> textField.layer.cornerRadius = 5;
> textField.backgroundColor = UIColor.lightGrayColor;
> ```

@andrewoverton yes I considered writing my own UITextField but a material design component textfield comes with the neat support for error and helper text, and more, which I am already using elsewhere in the same app, so I would like for consistency's sake to use the same field here. There was just one field which had a off-design where I needed indeed a UITextField default look-a-like configuration.
