### ISSUE TITLE
Consider making trackingScrollView a setter only.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#331] opened 2016-04-12 18:50 UTC
@property(nonatomic, weak, nullable) UIScrollView *trackingScrollView;
allows someone to:
appBar.headerViewController.headerView.trackingScrollView?.delegate = appBar.headerViewController; 

in this concrete case the delegate is a collectionViewDelegate and not a scrollViewDelegate.

**Comment by jverkoey** [comment] 2018-08-24 02:13
In practice the ability to read the API hasn't necessarily resulted in the mentioned code, so marking this as working as intended.

**Closed by jverkoey** 2018-08-24 02:13 UTC
Labels: Needs actionability review, Needs research, [FlexibleHeader], type:API change, type:Bug
