### ISSUE TITLE
2

### ISSUE THREAD

**Issue by id18522096554** [material-components/material-components-ios#10149] opened 2020-12-23 14:29 UTC
- [x] Measure internal usage of the API.
- [x] Create a GitHub issue.
- [x] Write a migration guide.
- [x] Add a comment to the API indicating that it will be deprecated.
- [x] Determine a schedule for the API deletion.
- [x] Announce that the API will be deprecated
- [x] After the deprecation date, annotate the API as deprecated.
- [x] After the deletion date, re-evaluate usage of the API.
- [x] Delete the API and migration guide.

**Comment by andrewoverton** [comment] 2020-12-23 22:28
Hello, I am going to close this because it is not clear what the issue is about. Please feel free to make it more clear and re-open. Thanks.

**Closed by andrewoverton** 2020-12-23 22:28 UTC
Labels: Needs actionability review
