### ISSUE TITLE
FR: Add Carthage support

### ISSUE THREAD

**Issue by jesusmateos1234** [material-components/material-components-ios#10116] opened 2020-11-09 23:15 UTC
## Feature Request/Suggestion

I need a support for Carthage, cause i don't use Cocoapods

## Additional context

It's pretty simple -> https://github.com/Carthage/Carthage

**Comment by jverkoey** [comment] 2020-11-10 14:38
Duplicate of https://github.com/material-components/material-components-ios/issues/75

**Closed by jverkoey** 2020-11-10 14:38 UTC
Labels: Needs actionability review
