### ISSUE TITLE
[Testing] Add support for snapshot testing

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4426] opened 2018-06-21 18:31 UTC
We should have tooling that runs A/B testing on screenshots generated during our testing phase.

**Comment by jverkoey** [comment] 2018-08-29 13:17
We now have internal snapshot testing as part of our release process. Adding external snapshot testing can/should be explored, with the caveat that it shouldn't significantly add to our presubmit turnaround times.

**Comment by jverkoey** [comment] 2018-10-01 19:30
Duplicate of https://github.com/material-components/material-components-ios/issues/5199

**Closed by jverkoey** 2018-10-01 19:30 UTC
Labels: Scripts, skill:Kokoro, skill:Scripting, type:Feature request
