### ISSUE TITLE
BottomNavigationBar's itemTitleFont should be nullable, not nonnull

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2829] opened 2018-01-11 19:52 UTC
As itemTitleFont is annotated UI_APPEARANCE_SELECTOR, it should be null.

**Comment by sigito** [comment] 2018-02-26 22:42
Duplicate of #2738.

**Comment by jverkoey** [comment] 2018-08-27 13:07
We no longer support UIAppearance, so marking as Obsolete.

**Closed by jverkoey** 2018-08-27 13:07 UTC
Labels: Obsolete, [BottomAppBar]
