### ISSUE TITLE
[Tabs] Item heights inconsistent with collectionView insets

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4118] opened 2018-05-10 14:09 UTC
```
The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the content insets top and bottom values.
```

This is an internal issue. If you are a Googler, please visit [b/37901472](http://b/37901472) for more details.

**Comment by romoore** [comment] 2018-08-21 18:08
Duplicate of #3220

**Closed by romoore** 2018-08-21 18:08 UTC
Labels: Internal, Needs actionability review, [Tabs]
