### ISSUE TITLE
[ActivityIndicator] Can't pod install anymore in a project with `pod 'MaterialComponents/ActivityIndicator'`

### ISSUE THREAD

**Issue by rickytribbia** [material-components/material-components-ios#9951] opened 2020-03-23 20:14 UTC
## Reproduction steps

1. Create new XcodeProject (tried with Xcode 11.3.1)
2. Go to project folder, `pod init`, add `pod 'MaterialComponents/ActivityIndicator'` into Podfile
3. try `pod install`

🧨

## Expected behavior

I expected that pod install just works

## Actual behavior

It doesn't work, got an error: 

```

### Error

JSON::ParserError - 434: unexpected token at ''
/usr/local/lib/ruby/gems/2.4.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.4.0/gems/json-2.2.0/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:715:in `from_string'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:689:in `from_file'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:186:in `specification'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:362:in `map'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

## Platform (please complete the following information)

 - OS: iOS
[materialactivitytest.zip](https://github.com/material-components/material-components-ios/files/4371703/materialactivitytest.zip)

**Comment by rickytribbia** [comment] 2020-03-24 07:59
It works with `pod 'MaterialComponents/ActivityIndicator', '~> 107.3'`

**Comment by jverkoey** [comment] 2020-03-25 16:38
Hey @rickytribbia thanks for the heads up on this, we will take a look soon.

**Comment by codeman7** [comment] 2020-03-25 17:05
Hey @rickytribbia I've tried to reproduce this issue by 
1. Creating a new Xcode project
2. Adding `pod 'MaterialComponents/ActivityIndicator'` to the podfile
3. Running `pod install`
4. Opening the `xcworkspace`
5. Building the app

I could not reproduce the issue. Is there a step I am missing? What steps did you take to cause the issue?

**Comment by rickytribbia** [comment] 2020-03-25 17:11
Try clearing cache, I can't run pod install without errors this way

**Comment by codeman7** [comment] 2020-03-25 17:19
I've run `pod cache clean --all` before running `pod install` and cannot reproduce

**Comment by codeman7** [comment] 2020-03-25 17:20
Downloading Xcode 11.3.1 to try to repro with that.

**Comment by codeman7** [comment] 2020-03-25 17:39
@wenyuzhang666 tried and couldn't repro with Xcode 11.3.1. @rickytribbia I'm going to close this issue for now, feel free to reopen with more steps to repro if you can't get it resolved.

**Closed by codeman7** 2020-03-25 17:39 UTC
Labels: type:Bug

**Comment by Ladegeraet** [comment] 2020-03-26 20:58
I have a similar error. `JSON::ParserError - 434: unexpected token at '{
      "name": "Button'`

**Comment by zslavman** [comment] 2020-05-21 17:56
have same problem with installation `pod 'MaterialComponents/ActivityIndicator'`

**Comment by andrewoverton** [comment] 2020-05-26 19:20
I don't think it's an issue with our library. Since it's a ruby error maybe it's an issue with the Ruby environment?
