### ISSUE TITLE
[Ink] [iOS] Broken links on App bars: bottom

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#4881] opened 2018-08-23 14:34 UTC
Links on [bottomappbar](https://material.io/develop/ios/components/bottomappbar) don't work:

1. https://material.io/components/ios/catalog/bottomappbar/api-docs/Enums/MDCBottomAppBarFloatingButtonElevation.html
2. https://material.io/components/ios/catalog/bottomappbar/api-docs/Enums/MDCBottomAppBarFloatingButtonPosition.html

**Comment by jverkoey** [comment] 2018-08-29 14:05
We publish the website once a month, so unfortunately these links tend to be broken for up to 30 days.

**Comment by romoore** [comment] 2018-08-29 14:08
Can you please clarify how the website links can be broken if the website is published all together?  The way it's described, it seems like we're frequently publishing a broken website and that should be a P0/P1 fix.

**Comment by romoore** [comment] 2018-08-29 14:08
Marking this client-blocking since clients cannot navigate material.io

**Comment by romoore** [comment] 2018-08-29 14:12
Related to #4805

**Comment by jverkoey** [comment] 2018-08-29 14:15
These are the links from our readmes, not from the website. The website is not yet serving any of our documentation from `develop`.

**Comment by jverkoey** [comment] 2018-08-29 14:16
Will mark this as a duplicate of https://github.com/material-components/material-components-ios/issues/4805 because it's the same underlying problem.

**Comment by romoore** [comment] 2018-08-29 14:16
@jverkoey  These are not links from the readmes, the URLs are all on material.io.

**Closed by jverkoey** 2018-08-29 14:16 UTC
Labels: Client-blocking, Website, Working as intended, [Ink], type:Bug

**Comment by romoore** [comment] 2018-08-29 14:17
Are you saying that since it's a bug with material.io we should not track it here? I think that's fair - we could open bugs against material.io and ask them to fix it.

**Comment by jverkoey** [comment] 2018-08-29 14:19
*sigh* I'm not sure how the website's being updated with our latest readmes but not our latest APIs. The website's only supposed to be updated once a month and all content should go with it. Let's move discussion to the internal bug on the other issue.
