### ISSUE TITLE
[AppBar] Changing the title of a navigationItem.rightBarButtonItem does not relayout the button

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3731] opened 2018-05-04 17:10 UTC
### Overview
In the Cards &rarr; Edit/Reorder example, the right bar button item defaults to "Edit" but when it is changed to "Reorder", only "R...r" appears because the button does not resize.

![simulator screen shot - iphone se - 2018-05-04 at 12 59 14](https://user-images.githubusercontent.com/1753199/39641509-7215f7be-4f9c-11e8-9cad-7fb34f2e5ed7.png)

### Reproduction steps
1. Create a navigationItem.rightBarButtonItem with a short title
1. Once on-screen, change the title to something longer

### Version number
55.0.1

### Operating system and device
iPhone SE/iOS 11.3 (Simulator)
iPhone X/iOS 11.3 (Simulator)

**Comment by AlimoRabbani** [comment] 2018-05-07 11:51
This may be related to #3692?

**Comment by jverkoey** [comment] 2018-08-27 17:03
Duplicate of https://github.com/material-components/material-components-ios/issues/1717.

**Closed by jverkoey** 2018-08-27 17:03 UTC
Labels: [NavigationBar], type:Bug
