### ISSUE TITLE
FeatureHighlightViewController can change prefers status bar hidden

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4126] opened 2018-05-10 14:09 UTC
https://github.com/material-components/material-components-ios/issues/861

As a developer, my app hides the status bar but MDCFeatureHighlightViewController doesn't. The child view controller should keep the same status bar behavior as its parent.

---

This is an internal issue. If you are a Googler, please visit [b/32840310](http://b/32840310) for more details.

---
#### Internal data
- Associated internal bug: [b/32840310](http://b/32840310)

**Comment by mohammadcazig** [comment] 2018-05-14 19:09
@jverkoey  I was not able to reproduce this on my sample project. However I am not sure how status bar was hidden through storyboard in the example you saw. Could you add more context or close this other wise?

**Comment by material-mirror** [comment] 2019-07-30 18:03
The internal issue [b/32840310](http://b/32840310) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 18:03 UTC
Labels: [FeatureHighlight], skill:Containment, type:Bug
