### ISSUE TITLE
[Dialogs] Followup work: changing buttons/actions memory structure

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5525] opened 2018-10-25 14:33 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/118394802](http://b/118394802) for more details.

---
#### Internal data
- Associated internal bug: [b/118394802](http://b/118394802)

**Comment by jverkoey** [comment] 2018-10-25 14:39
Duplicate of https://github.com/material-components/material-components-ios/issues/5447

**Closed by jverkoey** 2018-10-25 14:39 UTC
Labels: Internal, Needs actionability review, [Dialogs], type:Feature request
