### ISSUE TITLE
[List] Cannot inherit MDCCell under Swift 5

### ISSUE THREAD

**Issue by aUcidme** [material-components/material-components-ios#7014] opened 2019-03-31 17:14 UTC
Cannot inherit any kinds of Cells under Swift 5, which would be reported an error because of the library declaration of the cell. 

---
#### Internal data
- Associated internal bug: [b/129672122](http://b/129672122)

**Comment by romoore** [comment] 2019-04-01 12:31
Thanks @aUcidme . Could you please post a snippet of the code causing trouble and of the error you're seeing from the build system?

**Comment by aUcidme** [comment] 2019-04-01 12:37
Thank you for your quick response. I've never post issues before, so if there are any problems on format or content, I would apologize for that.

Here are the screenshots about the error,
![errors](https://user-images.githubusercontent.com/22599097/55327867-9f51c880-54bd-11e9-992c-ce0a2ca52f54.png)
 
![language version](https://user-images.githubusercontent.com/22599097/55327877-a678d680-54bd-11e9-9b8e-1b4054a4bce6.png)

If I modify the "Swift Language Version" in "Build Settings" to "Swift 5", these errors come out.

**Comment by romoore** [comment] 2019-04-01 12:42
Awesome, thanks for the screenshot.  For ease of indexing and screen readers, here's the error:

## Swift Compiler Error

* Cannot inherit from non-open class 'MDCSelfSizingStereoCell' outside of its defining module.
*NoteCell.swift*
* Cannot inherit from non-open class 'MDCAppBarNavigationController' outside of its defining module.
*NavigationController.swift*

**Comment by jverkoey** [comment] 2019-05-21 02:27
Hi @aUcidme, these errors are by design; we have intentionally restricted subclassing of these components in favor of compositional solutions. I'm going to close this issue as working as intended, but please feel free to share the problem you're trying to solve as a new issue.

**Closed by jverkoey** 2019-05-21 02:27 UTC
Labels: [List], skill:Swift, type:Bug
