### ISSUE TITLE
[Catalog] HeaderStackViewTypicalUse example overlaps status bar on iPhone X

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1968] opened 2017-09-13 12:53 UTC
### Overview
Our "Reveal" button is overlapping the status bar area.

![hsv-typical-iphonex](https://user-images.githubusercontent.com/1753199/30378273-9f2507d0-98cd-11e7-8557-f8c5079aabee.png)

### Reproduction steps
Open MDC Catalog on iPhone X Simulator

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

**Comment by chuga** [comment] 2017-09-19 20:41
Marking as a duplicate of #2009 as this seems to be a NavBar issue

**Closed by chuga** 2017-09-19 20:41 UTC
Labels: device:iPhone X, type:Visual bug, where:Catalog
