### ISSUE TITLE
[ButtonBar] MDCAppBarButtonBarBuilder naming is confusing

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#3418] opened 2018-04-20 12:54 UTC
MDCButtonBar uses an MDCButtonBarDelegate object for laying out the buttons in the button bar.

This delegate is always set to an MDCAppBarButtonBarBuilder object. Therefore, MDCButtonBar always uses MDCAppBarButtonBarBuilder to layout the buttons, regardless of whether it is in a navigation bar or not.

I believe this is the result of a deprecation and cleanup from a long time ago: https://github.com/material-components/material-components-ios/commit/f6bbf8ac35043ff89b4996296de7e1bcc90955d7 and https://github.com/material-components/material-components-ios/commit/f7c84317ec01774be169bd3486ebb8a561376250

There are 3 possible ways to address the confusion:
1. Fold MDCAppBarButtonBarBuilder into MDCButtonBar and remove MDCButtonBarDelegate altogether.
2. Rename MDCAppBarButtonBarBuilder to something that doesn't suggest it's limited to MDCAppBar or MDCNavigationBar.
3. Make the delegate customizable, which is probably undesired and against the whole point of https://github.com/material-components/material-components-ios/commit/f6bbf8ac35043ff89b4996296de7e1bcc90955d7

---
https://www.pivotaltracker.com/story/show/156952507

**Comment by jverkoey** [comment] 2018-04-20 14:15
Wonderful. Thank you! I'll create an epic to track resolution of this in pivotal.

**Comment by jverkoey** [comment] 2018-04-20 14:16
Option 1 is the preferred route.

**Comment by jverkoey** [comment] 2018-08-27 13:07
Duplicate of https://github.com/material-components/material-components-ios/issues/559

**Closed by jverkoey** 2018-08-27 13:07 UTC
Labels: [ButtonBar]
