### ISSUE TITLE
[Tabs] MDCTabBar does not provide a way to get notified when a tab is loaded.

### ISSUE THREAD

**Issue by mrhappyasthma** [material-components/material-components-ios#6275] opened 2019-01-10 19:14 UTC
Other tab bar implementations in the past have included something along the lines of `willDisplayItem:` and `didEndDisplayingItem`. These are useful for things like logging impressions of a new tab appearing.

## Potential Solution
* Expose a `- (UIView *)viewForItem:(UITabBarItem *)` API similar to BottomNavigation
* Expose a `@property(nonatomic, weak) id<UIScrollViewDelegate> itemScrollDelegate;` API that allows observation of scroll events within the tabs.

## Alternative Solution
* Expose `visibleItems` property a la UICollectionView
* Expose pass-through methods for `-collectionView:willDisplayCell:forItemAtIndexPath:` that instead provide `forTabBarItem:`

---
#### Internal data
- Associated internal bug: [b/122968550](http://b/122968550)
- Blocked by:

**Comment by romoore** [comment] 2019-01-11 14:01
@mrhappyasthma Do you have an example in UIKit where this type of API is provided for UITabBar? Looking briefly at the headers, I don't see something like this available. Is there a different API (maybe not exactly `willDisplayItem:`) that you have used to generate these events indirectly?

**Comment by mrhappyasthma** [comment] 2019-01-11 18:21
Ah, I don't see anything like this on UITabBar. I was referring to internal implementations of the tab bar. I don't see any way to get the "visible" set of tabs from UITabBar.

This was based primarily off of classes like UITableView and UICollectionView which show a subset of cell and allow scrolling to reveal more cells. (I.e. scrollView behavior). However maybe we don't want to expose either of those directly because we don't want to be tied too tightly to a given implementation.

Will discuss offline.

**Comment by romoore** [comment] 2019-01-11 20:42
We need to test the behavior of UICollectionView and when it calls the `willDisplayCell` delegate methods. We should also be careful about using these methods and only stick to UIKit's guaranteed (public) behavior.

**Comment by mrhappyasthma** [comment] 2019-01-14 23:33
The current action item here is to test/document the behavior of `-collectionView:willDisplayCell:forItemAtIndexPath:` in regards to pre-fetching of collection views.

Once we fully understand the behavior of this, the MDC team can make a decision on one of the alternatives mentioned in the updated 1st post in this thread.

**Comment by andrewoverton** [comment] 2019-06-07 15:40
Closed by https://github.com/material-components/material-components-ios/pull/7518

**Comment by jverkoey** [comment] 2019-06-10 17:00
#7518 was reverted as part of the most recent release, so this issue is being re-opened.

**Comment by romoore** [comment] 2019-06-10 17:09
Here's an excerpt from the crash caused by replacing one view controller with another:

```
2019-06-10 08:57:30.230 XCTRunner[26456:1797487] Uncaught exception in Application: *** -[__NSArrayI objectAtIndexedSubscript:]: index 3 beyond bounds [0 .. 2]
0   CoreFoundation                      0x000000010f95b1bb __exceptionPreprocess + 331
1   libobjc.A.dylib                     0x0000000114d16735 objc_exception_throw + 48
2   CoreFoundation                      0x000000010f8a74ec _CFThrowFormattedException + 194
3   CoreFoundation                      0x000000010f9ddb00 +[__NSArrayI allocWithZone:] + 0
4   <TestHost>                   0x000000010b623d2d -[MDCItemBar collectionView:didEndDisplayingCell:forItemAtIndexPath:] + 37
5   UIKitCore                           0x00000001175f212d -[UICollectionView _notifyDidEndDisplayingCellIfNeeded:forIndexPath:] + 195
6   UIKitCore                           0x00000001176091cb -[UICollectionView _reuseCell:notifyDidEndDisplaying:] + 1428
7   UIKit                               0x0000000134a3a638 -[UICollectionViewAccessibility _reuseCell:notifyDidEndDisplaying:] + 77
8   CoreFoundation                      0x000000010f9ce342 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
9   UIKitCore                           0x00000001175ee749 __30-[UICollectionView reloadData]_block_invoke + 168
10  UIKitCore                           0x00000001175ee20b -[UICollectionView reloadData] + 404
11  UIKit                               0x0000000134a3a200 -[UICollectionViewAccessibility reloadData] + 42
12  <TestHost>                   0x000000010b624dac -[MDCItemBar reload] + 38
13  <TestHost>                   0x000000010b622b80 -[MDCItemBar setItems:] + 303
14  <TestHost>                   0x000000010b621c30 -[MDCTabBarViewController updateTabBarItems] + 773
15  <TestHost>                   0x000000010b621475 -[MDCTabBarViewController updateOldViewControllers:to:] + 621
16  <TestHost>                   0x000000010b6211ec -[MDCTabBarViewController setViewControllers:] + 120
```

**Comment by material-mirror** [comment] 2019-06-10 17:19
The internal issue [b/122968550](http://b/122968550) is now closed. This issue is being closed as a result.

**Closed** 2019-06-14 19:32 UTC
Labels: [Tabs], type:Feature request
