### ISSUE TITLE
[Tabs] We don't have a minimum/maximum width

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#4458] opened 2018-06-29 19:26 UTC
The guidelines state a minimum width of 90dp and 360dp for scrollable tabs

1. Go to Dragons
2. Go to TabBar
3. Click "TextTabs"

## Expected behavior

All tabs should be a minimum of 90dp or a maximum of 360dp

## Actual behavior

Certain tabs don't respect this

<img width="769" alt="screen shot 2018-06-29 at 3 24 17 pm" src="https://user-images.githubusercontent.com/7131294/42110852-902968c2-7bb0-11e8-82aa-5cac7f782ff1.png">

Currently 34dp

<img width="757" alt="screen shot 2018-06-29 at 3 24 30 pm" src="https://user-images.githubusercontent.com/7131294/42110876-a5675f28-7bb0-11e8-9704-b52e28415200.png">

Currently 469dp

## Platform (please complete the following information)

iPhone X/iPad Air 2/iOS 11.4

---
#### Internal data
- Associated internal bug: [b/117178423](http://b/117178423)

**Comment by romoore** [comment] 2019-05-07 15:32
Duplicate of https://github.com/material-components/material-components-ios/issues/2029

**Closed** 2019-05-07 15:31 UTC
Labels: [Tabs], type:Bug
