### ISSUE TITLE
section Header issue when shiftBehavior is enable Using AppBar 

### ISSUE THREAD

**Issue by adelbios** [material-components/material-components-ios#2542] opened 2017-11-30 01:42 UTC
this video explain my issue and that's my code please i wanna help
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16545509/33408658-bf1ed456-d588-11e7-9ac2-af9d710d4b89.gif)

and that's my code 

```swift
    class TestView: UITableViewController {

    let appBar = MDCAppBar()
    let sectionTitle = ["A" , "B" , "C" ,"D"]
    
    override func viewDidLoad() {
        super.viewDidLoad()

        addChildViewController(appBar.headerViewController)
        appBar.headerViewController.headerView.backgroundColor = UIColor.black
        appBar.headerViewController.headerView.trackingScrollView = self.tableView
        appBar.navigationBar.titleTextAttributes = [NSAttributedStringKey.foregroundColor: UIColor.white]
        appBar.navigationBar.tintColor = UIColor.white
        appBar.navigationBar.isOpaque = true
        appBar.addSubviewsToParent()
        self.title = "Demo"
        
        self.appBar.headerViewController.headerView.shiftBehavior = .enabled
        self.appBar.headerViewController.headerView.hide(whenShifted: self.appBar.headerStackView)
        
    }

  
    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        // #warning Incomplete implementation, return the number of sections
        return  self.sectionTitle.count
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete implementation, return the number of rows
        return 5
    }

    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = tableView.dequeueReusableCell(withIdentifier: "CELL")
        
        if cell == nil {
            cell = UITableViewCell(style: UITableViewCellStyle.value1, reuseIdentifier: "CELL")
        }
        
        cell!.textLabel?.text = "Baking Soda"
        cell!.detailTextLabel?.text = "1/2 cup"
     
  

        return cell!
    }

    override func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return self.sectionTitle[section]
    }
    
  override  func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 70
    }

    
   override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if scrollView == appBar.headerViewController.headerView.trackingScrollView {
            appBar.headerViewController.headerView.trackingScrollDidScroll()
            
        }
    
        
    }
    
  override  func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if scrollView == appBar.headerViewController.headerView.trackingScrollView {
            appBar.headerViewController.headerView.trackingScrollDidEndDecelerating()
            
        }
    }
    
  override  func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        if scrollView == appBar.headerViewController.headerView.trackingScrollView {
            let headerView = appBar.headerViewController.headerView
            headerView.trackingScrollDidEndDraggingWillDecelerate(decelerate)
        }
    }
    
   override func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        if scrollView == appBar.headerViewController.headerView.trackingScrollView {
            let headerView = appBar.headerViewController.headerView
            headerView.trackingScrollWillEndDragging(withVelocity: velocity, targetContentOffset: targetContentOffset)
            
        }
    }
    

}
```

**Comment by adelbios** [comment] 2017-12-01 02:10
please i wanna helpe

**Comment by romoore** [comment] 2017-12-01 14:03
Hi @adelbios. Thanks for your interest in MDC-iOS!  I confirmed that this is a limitation with the current component implementations. For example, I can take the `AppBarSectionHeadersExample` and change the `shiftBehavior` to `.enabled` and see the same visual defect. Similarly, I can increase the `maximumHeight` of the `headerView` and the tableview's headers won't shift as expected.

The team may not have a chance to get to this bug right away. If you have an idea for a fix, we gladly welcome pull requests.

**Comment by adelbios** [comment] 2017-12-01 20:01
sorry but i have no idea for right now

**Comment by adelbios** [comment] 2017-12-02 20:26
can someone help to fix this ussue

**Comment by BigAlInTheHouse** [comment] 2017-12-03 08:05
Sent from Yahoo Mail on Android 
 
  On Sat, Dec 2, 2017 at 2:26 PM, adelbios<notifications@github.com> wrote:   
can someone help to fix this ussue

**Comment by adelbios** [comment] 2017-12-03 18:55
What?!

**Comment by jverkoey** [comment] 2018-08-24 13:45
Duplicate of https://github.com/material-components/material-components-ios/issues/2032.

**Closed by jverkoey** 2018-08-24 13:45 UTC
Labels: Needs actionability review, [AppBar], type:Bug
