### ISSUE TITLE
[MDCTextField] contentView user interaction disabled when tapped below the placeholder TF doesn't become first responder

### ISSUE THREAD

**Issue by GabrieleNardi** [material-components/material-components-ios#7175] opened 2019-04-18 16:18 UTC
If tap is over the placeholder textfield become first responder else not.

• add textfiled to main view
• add constraints
• run
• tap into it

## Expected behavior

I expect that if I tap all over the TextField it becomes first responder.

## Actual behavior
![textfield](https://user-images.githubusercontent.com/33030359/56375544-26b17280-6206-11e9-8acf-3b1ebd454d88.gif)

## Platform

Device: iPad Air 2 
OS: iOS 12.1

---
#### Internal data
- Associated internal bug: [b/131061052](http://b/131061052)

**Comment by bryanoltman** [comment] 2019-11-13 20:07
Cannot reproduce, closing

**Closed by bryanoltman** 2019-11-13 20:07 UTC
Labels: [TextFields], type:Bug
