### ISSUE TITLE
[Snackbar] Error for SnackBar example in Legacy/New mode

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#4654] opened 2018-07-27 14:30 UTC
App error when running the Snackbar example in the catalog in after toggling Legacy/New modes.

Steps:

- Open the SnackBar demo, then tap "Start Demo"
- Select "Simple Snackbar"
- Tap "Legacy" 
- Select "Simple Snackbar" again
- Toggle back to "New" 
- Select "Simple Snackbar" one more time -> EXC_BAD_ACCESS

**Comment by romoore** [comment] 2018-07-27 23:22
Duplicate of #3723

**Closed by romoore** 2018-07-27 23:22 UTC
Labels: Needs actionability review, [Snackbar]
