### ISSUE TITLE
[BottomNavigation] Ink color only matches tint for first tab item.

### ISSUE THREAD

**Issue by bambaragoogle** [material-components/material-components-ios#4937] opened 2018-08-28 21:18 UTC
After setting a MDCBottomNavigationBar's selectedItemTintColor property, only the first tab item's ink changes to that tint color. The documentation doesn't specify, but I would expect this property to affect either all tab ink or none of it. If it's not intended to change the ink color, please expose an additional property that exposes ink color.

**Comment by romoore** [comment] 2018-08-29 13:18
Thanks, @bambaragoogle . Could you please provide steps to reproduce? We recently merged #4420 that should have demonstrated the fix.

**Comment by romoore** [comment] 2018-08-29 13:19
Oh, whoops, you want the itemTintColor to affect the ink color. #4420 is unrelated.

**Comment by romoore** [comment] 2018-08-29 13:32
I tried to reproduce this in a default-themed MDCCatalog (not using our black/grey theme customizations) and could not reproduce the issue you are describing. It seems as though the ink color is changing and is correctly based on the `selectedItemTintColor` when I test several situations:

1. The initial (default) state
2. When I change the `selectedItemTintColor` and `unselectedItemTintColor`
3. When I reapply the original values (idempotency)
4. With a white background to show which tint is being used for the Ripple

|State|Default | Changed | Default Reapplied (idempotency) | Tint highlighted|
|--|--|--|--|--|
|Unselected|![unselected-1-default](https://user-images.githubusercontent.com/1753199/44790580-af8f7700-ab6d-11e8-83fb-ede9955ae3e1.png)|![unselected-2-changed](https://user-images.githubusercontent.com/1753199/44790585-b322fe00-ab6d-11e8-9281-566c963aac22.png)|![unselected-3-reapply](https://user-images.githubusercontent.com/1753199/44790592-b6b68500-ab6d-11e8-91bb-3574576b97af.png)|![unselected-4-tintcolor](https://user-images.githubusercontent.com/1753199/44790691-ea91aa80-ab6d-11e8-89e7-9114109eec19.png)|
|Selected|![selected-1-default](https://user-images.githubusercontent.com/1753199/44790712-fe3d1100-ab6d-11e8-8ef7-083bbefae941.png)|![selected-2-changed](https://user-images.githubusercontent.com/1753199/44790724-02692e80-ab6e-11e8-9225-e87342ae8061.png)|![selected-3-reapply](https://user-images.githubusercontent.com/1753199/44790754-144ad180-ab6e-11e8-977a-33f96c7dd7d9.png)|![selected-4-tintcolor](https://user-images.githubusercontent.com/1753199/44790765-19a81c00-ab6e-11e8-888d-c82e8e95fd30.png)|

Could you please provide a code snippet or steps to reproduce the bug you are seeing?

**Comment by bambaragoogle** [comment] 2018-08-29 16:11
Hi Robert. Thanks for clarifying the issue above. Here's some steps to reproduce:

1. Initialize the MDCBottomNavigationBar.
1. Populate the `items` property with a list of `UITabBarItem`s. This probably doesn't matter, but mine each have a title and image.
1. Assign some easily-distinguishable color to the `selectedItemTintColor` property, for example `UIColor.greenColor`.
1. Do not set the `unselectedItemTintColor` property. (The value for this is the default of `UIExtendedGrayColorSpace 0.5 1`).

Observed effect:
The selected tab images and titles are green, and the unselected ones are gray (this is expected behavior).
For the first item, tapping on it produces an ink effect with green color (this is expected behavior).
For all items other than the first one, tapping them produces a gray ink effect.

**Closed** 2018-08-31 03:50 UTC
Labels: [BottomNavigation], type:Bug
