### ISSUE TITLE
[Collections] Collections does not respect the safe area on landscape on iPhone X

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1980] opened 2017-09-14 07:47 UTC
### Overview
On iPhone X, the collection with MDC Card style is not respecting the safe area, hiding some content.
![simulator screen shot - iphone x - 2017-09-14 at 09 42 31](https://user-images.githubusercontent.com/1257452/30417895-892ccf44-9931-11e7-94ac-98daec595a8f.png)

### Reproduction steps
Launch MDC Catalog on iPhone X → Collections → Demo

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

**Comment by chuga** [comment] 2017-09-19 19:58
Marking it as a duplicate of #2006

**Closed by chuga** 2017-09-19 19:58 UTC
Labels: device:iPhone X, type:Visual bug, where:Collections
