### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [material-components/material-components-ios#1102] opened 2016-12-21 16:30 UTC
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://goo.gl/8AMTfw)
- [Carthage Tutorial: Getting Started](https://goo.gl/9pVzFX)
- [Making Carthage-compatible Frameworks with Swift](https://goo.gl/SzPe8j)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](https://goo.gl/mzZ3Si) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by ajsecord** [comment] 2016-12-21 16:38
Thanks! It's definitely on our radar.

**Comment by ajsecord** [comment] 2017-01-03 21:26
Actually, this is a dupe of #75, I missed that we had already filed this a while ago.

**Closed by ajsecord** 2017-01-03 21:26 UTC
Labels: is:Help wanted, Triaged, type:Feature request
