### ISSUE TITLE
Could not build Objective-C module 'MaterialComponentsAlpha' 

### ISSUE THREAD

**Issue by satheeshkumar8186** [material-components/material-components-ios#5380] opened 2018-10-10 07:21 UTC
Then I trying to integrate Both MaterialComponents and MaterialComponentsAlpha to my swift project I am getting this error **"Could not build Objective-C module 'MaterialComponentsAlpha' "** , 

I tried creating bridge header and Imported <MaterialComponentsAlpha> but It didn't work and it is throughs error "MaterialComponentsAlpha file didnt find" .

The given below is my pod file.

```ruby
target 'MaterialDesign' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaterialDesign
  pod 'MaterialComponents'
  pod 'MaterialComponentsAlpha', :git => 'https://github.com/material-components/material-components-ios.git'
end
```

how to use both MaterialComponentsAlpha and MaterialComponents in the swift project.

---
#### Internal data
- Associated internal bug: [b/117594919](http://b/117594919)

**Comment by andrewoverton** [comment] 2018-10-12 15:08
Hi @satheeshkumar8186, pardon this inconvenience! Could you please try again? I think the problem has been addressed.

**Comment by mpasumarthi** [comment] 2018-10-22 03:41
I am also facing the same issue with the latest. Can someone help me out how to use it?
![screenshot 2018-10-22 at 9 10 51 am](https://user-images.githubusercontent.com/22295472/47277109-70fcc280-d5da-11e8-8c37-4f91692e3963.png)

![screenshot 2018-10-22 at 9 09 40 am](https://user-images.githubusercontent.com/22295472/47277100-4874c880-d5da-11e8-8877-f449266ae4af.png)

**Comment by codeman7** [comment] 2018-10-25 19:40
The dependency headers are in a different target than the dependent headers so the can't "see" them.

**Comment by codeman7** [comment] 2018-10-25 19:51
<img width="957" alt="screen shot 2018-10-25 at 3 49 50 pm" src="https://user-images.githubusercontent.com/7131294/47526461-c4d30a00-d86d-11e8-98fc-2cd49d2dde16.png">
<img width="956" alt="screen shot 2018-10-25 at 3 49 40 pm" src="https://user-images.githubusercontent.com/7131294/47526465-c7cdfa80-d86d-11e8-9a9d-bf1affc95155.png">

**Comment by codeman7** [comment] 2018-10-25 19:51
If you manually add all of the required headers to the MaterialComponentsAlpha headers then the problem is solved.

**Comment by jverkoey** [comment] 2018-10-25 19:53
Is MaterialComponents listed in any manner as a dependency of MaterialComponentsAlpha in Xcode?

**Comment by codeman7** [comment] 2018-10-25 19:55
MaterialComponents/BottomSheet, MaterialComponents/Ink, and MaterialComponents/Typography are listed as dependencies in the Podspec file

**Comment by jverkoey** [comment] 2018-10-25 19:55
Are they listed as dependencies in the MaterialComponentsAlpha Xcode target?

**Comment by codeman7** [comment] 2018-10-25 19:58
Yes, MaterialComponentAlpha - Target Dependency - is MaterialComponents (Pod)

**Comment by codeman7** [comment] 2018-10-25 19:59
We need to somehow have `component.public_header_files` include `component.dependency.public_header_files`

**Comment by codeman7** [comment] 2018-10-25 20:06
Could possibly be USER_HEADER_SEARCH_PATH or FRAMEWORK_SEARCH_PATH

**Comment by beraybentesen** [comment] 2019-03-07 07:26
Any news about this problem? The problem still occurs.

**Comment by romoore** [comment] 2019-03-07 13:45
Reopening since @beraybentesen is reporting that it's still reproducible.

@beraybentesen  Could you please provide the relevant portion of your Podfile here? It's helpful for us to see which Material Components you're importing and how you're handling MaterialComponentsAlpha.

**Comment by material-mirror** [comment] 2019-03-07 13:49
The internal issue [b/117594919](http://b/117594919) is now closed. This issue is being closed as a result.

**Comment by andrewoverton** [comment] 2019-03-07 16:45
@beraybentesen is the issue you're currently experiencing related to what I describe in [this comment](https://github.com/material-components/material-components-ios/issues/6782#issuecomment-470601600)?

**Comment by andrewoverton** [comment] 2019-03-08 15:14
I am able to build now that v79.0.0 has landed. I'm going to close this. Please reopen if you are still able to reproduce the issue!

**Closed by andrewoverton** 2019-03-08 15:14 UTC
Labels: skill:CocoaPods, type:Question
