### ISSUE TITLE
[TextFields] EditText field with label support

### ISSUE THREAD

**Issue by nneuberger1** [material-components/material-components-ios#1357] opened 2017-05-03 17:04 UTC
Does this library support EditText field that includes animation of the "hint" text that dynamically moves up to a label up clicking the field.  This is a feature within Anrdoid and I'm looking for the 
same behavior on iOS.

Here's some of the spec for labels above EditText fields in Android.
https://material.io/guidelines/components/text-fields.html#text-fields-layout

Here's an example implementation on Android.
http://www.androidhive.info/2015/09/android-material-design-floating-labels-for-edittext/

I didn't see any edit text controls in the repository and wondering if that support exists.  If not, would be a feature that can pulled into this project if built?

Thanks...

**Comment by willlarche** [comment] 2017-05-04 14:32
Hi! Thanks for inquiring. 

We actually are days away from having textfields as a component in the repo. You can monitor the progress of the pull request #1318 which houses that code.

**Comment by willlarche** [comment] 2017-05-04 14:34
Closing as duplicate of #788 .

**Closed by willlarche** 2017-05-04 14:34 UTC
Labels: where:TextField

**Comment by nneuberger1** [comment] 2017-05-04 15:13
Nice!  I'll keep an eye on it.  Thanks...

**Comment by willlarche** [comment] 2017-05-04 17:46
Any time!
