### ISSUE TITLE
[ProgressView] MDCProgressView does not have accessibility label and fails accessibility tests

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6413] opened 2019-01-18 14:45 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/123068208](http://b/123068208) for more details.

---
#### Internal data
- Associated internal bug: [b/123068208](http://b/123068208)

**Comment by jverkoey** [comment] 2019-11-11 21:09
Duplicate of https://github.com/material-components/material-components-ios/issues/7603

**Closed by jverkoey** 2019-11-11 21:09 UTC
Labels: Accessibility, [ProgressView], skill:UIAccessibility, type:Bug
