### ISSUE TITLE
[TextFields] errorText multiple lines

### ISSUE THREAD

**Issue by ivangodfather** [material-components/material-components-ios#4476] opened 2018-07-04 09:35 UTC
When i set a longer error than the width of the textfield it cuts instead of going to next line.

## Reproduction steps

controller.setErrorText("This text is longer than the width of the textField", errorAccessibilityValue: nil)

## Expected behavior

The error should be displayed in required lines as of:
[Image](https://material.io/design/assets/1WrZZKbP3jMNcVRn2VT-WGrS_9olLrZf_/textfields-anatomy-error-caution.png)

## Actual behavior

![screen shot 2018-07-04 at 11 27 39](https://user-images.githubusercontent.com/1838117/42269327-27801ae2-7f7e-11e8-9628-69684ba0f71e.png)

## Platform (please complete the following information)

Material version 56.0.0

---
#### Internal data
- Associated internal bug: [b/117178075](http://b/117178075)

**Comment by willlarche** [comment] 2018-07-11 18:51
Related issue #1924

**Comment by jverkoey** [comment] 2018-10-25 21:40
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by romoore** [comment] 2019-01-31 00:00
Closing as a duplicate of https://github.com/material-components/material-components-ios/issues/5762 . Although this issue is older, there's more context/work being done (primarily internally) around https://github.com/material-components/material-components-ios/issues/5762.

**Closed by romoore** 2019-01-31 00:00 UTC
Labels: [TextFields], skill:Auto Layout, type:Feature request
