### ISSUE TITLE
[TextFields] Can get an gap in the outline where placeholder label should be

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6059] opened 2018-12-19 18:15 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/121220012](http://b/121220012) for more details.

---
#### Internal data
- Associated internal bug: [b/121220012](http://b/121220012)

**Comment by romoore** [comment] 2018-12-20 04:21
Duplicate of #5948

**Closed by romoore** 2018-12-20 04:21 UTC
Labels: [TextFields], type:Bug
