### ISSUE TITLE
[Tabs] TabBarItems not show, iOS 9,10

### ISSUE THREAD

**Issue by TyM6JIep** [material-components/material-components-ios#2199] opened 2017-10-16 20:47 UTC
### Overview
TabBarItems not showing on iOS 9,10

iPhone 4s, 5s
iOS 9, 10
![1](https://user-images.githubusercontent.com/10204911/31634370-ae6dbc2c-b2dc-11e7-8c4d-8fffdc55b3f4.png)

iPhone 7,7+
iOS 11
![2](https://user-images.githubusercontent.com/10204911/31634375-b16b6316-b2dc-11e7-8da8-0c54d7892675.png)

### Reproduction steps
Please see [example](https://github.com/TyM6JIep/material-components-tabs.git)
If tap on first or second button we will see:
1) only MDCTabBar with TabBarItems - ok
2) navigationBar and MDCTabBar under it with TabBarItems - ok

but if tap on third button we will see empty MDCTabBar under navigationBar

If will launch this example on iOS 11 all work perfectly.

### Version number
 - 35.3.0

### Operating system and device
iPhone 4s, 5s, iOS 9,10

**Comment by chuga** [comment] 2017-10-27 19:11
So when the MDCTabBar is used in a VC that's the root view controller of a UINavigationController, used inside of a UITabBarController, the collection view in MDCItemBar gets a contentSize of {0, 0}. This is not caused by MDCItemBarFlowLayout, as the same thing happens when UICollectionViewFlowLayout is used.

I tried a few things but couldn't find a way to fix this bug. Since this is not related to any iOS 11 changes, I'm assigning this to @brianjmoore as he's the owner of this component.

**Comment by chuga** [comment] 2017-10-27 20:15
@TyM6JIep In the meantime, and if you haven't already, I'd give MDCTabBarViewController a try.

**Comment by TyM6JIep** [comment] 2017-10-29 15:33
@chuga Thank you, i will try

**Comment by brianjmoore** [comment] 2017-10-30 16:22
The screenshots here indicate to me that these are tabs on the top of the screen, which MDCTabBarViewController unfortunately doesn't support.

**Comment by brianjmoore** [comment] 2017-10-30 19:03
This is caused by `automaticallyAdjustsScrollViewInsets`-based inset adjustment. UIKit is reaching into the scroll view inside the tab bar and adding top insets to it, which breaks the tab bar's layout logic.

This is not something we can support, beyond documenting this issue here. My recommendation would be to:
* Manage insets manually and set `automaticallyAdjustsScrollViewInsets` to `false`
* Add a non-scrolling view at index 0 to defeat automatic adjustment. (However, this is relying on undocumented behavior.)

      let dummyView = UIView(frame: .zero)
      dummyView.isHidden = true
      view.addSubview(dummyView)

Applying either of these approaches to your sample project appears to fix the issue.

See this post with general recommendations here:
https://useyourloaf.com/blog/extra-space-when-embedding-table-views/

**Closed by brianjmoore** 2017-10-30 19:03 UTC
Labels: priority:high, type:Visual bug, where:TabBar

**Comment by TyM6JIep** [comment] 2017-10-31 12:42
Excellent! It's work. Thank you very much.
