### ISSUE TITLE
[FlexibleHeader] FlexibleHeader should respect the safe area on iPhone X

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1995] opened 2017-09-18 15:37 UTC
### Overview
By default the flexible header has the size of the status bar hard coded.
```objective-c
// The default maximum height for the header. Includes the status bar height.
static const CGFloat kFlexibleHeaderDefaultHeight = 76;
```
This does not work with the safe area, as the size of the status bar can change.

As the size of the flexible header can be set, it is not possible to directly take into account the safe area.
The  behavior of the properties setting the size of the flexible header might have to be changed to not take into account the height of the toolbar.

![simulator screen shot - iphone x - 2017-09-18 at 17 34 26](https://user-images.githubusercontent.com/1257452/30550404-a825a448-9c97-11e7-97a4-7467a11e11c0.png)

### Reproduction steps
 - The easiest way to see the problem is to check the size offered to the AppBar on the different screens on iPhone X: The AppBar is displayed too high.

### Version number
 - 34.0

### Operating system and device
- iOS 11, iPhone X

**Comment by chuga** [comment] 2017-09-19 20:36
Marking as a duplicate of #2008

**Closed by chuga** 2017-09-19 20:36 UTC
