### ISSUE TITLE
flexibleHeaderViewController:flexibleHeaderViewFrameDidChange: callback is invoked without actual frame changes

### ISSUE THREAD

**Issue by jpsachse** [material-components/material-components-ios#4994] opened 2018-09-04 08:41 UTC
The flexibleHeaderViewFrameDidChange callback in MDCFlexibleHeaderViewLayoutDelegate sounds like it should be invoked, whenever the frame of the header view changes. However, It is also invoked when the frame stays constant, but the trackingScrollView offset changes (i.e., when the header view has reached its maximum or minimum size, should not overextend and scrolling continues in the corresponding direction).

## Reproduction steps

Have a flexible header with minimum and maximum height set and a tracking scrollview.
Implement the flexibleHeaderViewFrameDidChange callback, e.g., with logging the current frame of the header view.
Scroll.

## Expected behavior

The callback is invoked every time the frame changes.

## Actual behavior

The callback is invoked every time the frame changes and whenever the scrollview offset changes without actually changing the frame of the header. This is a bit confusing, as the method is called flexibleHeaderViewFrameDidChange and may have negative performance impact when the header layout is actually adjusted upon frame size changes, as the corresponding calculations are done even though unnecessary.

## Platform (please complete the following information)

 - Device: Simulator
 - OS: iOS 9+

---
#### Internal data
- Associated internal bug: [b/117175796](http://b/117175796)

**Comment by jverkoey** [comment] 2018-09-04 20:21
Thanks for filing! I'm labeling this as a risky change because it's possible that clients are currently depending on this actual behavior. I agree that the expected behavior is likely ideal, but we may need to change this behavior using a runtime flag in order to allow clients to migrate gracefully.

**Comment by material-mirror** [comment] 2019-07-30 17:57
The internal issue [b/117175796](http://b/117175796) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 17:57 UTC
Labels: [FlexibleHeader], risky:Behavioral change, type:Bug
