### ISSUE TITLE
[FlexibleHeader] Internal issue: b/142322977

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8550] opened 2019-10-08 17:45 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/142322977](http://b/142322977) for more details.

---
#### Internal data
- Associated internal bug: [b/142338170](http://b/142338170)

**Comment by yarneo** [comment] 2019-10-08 19:52
This seems like a dupe of #8551 but by closing it i may close the internal issue so leaving it open.

**Closed** 2020-04-09 17:43 UTC
Labels: [FlexibleHeader], type:Feature request
