### ISSUE TITLE
URLs in comments are including parentheses

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#209] opened 2016-03-25 15:47 UTC
The ')' at the end of the line with the URL is being included in the URL (it's blue and follows if you open the URL)
![screen shot 2016-03-25 at 11 45 01 am](https://cloud.githubusercontent.com/assets/1271525/14047628/5ef5ab06-f27f-11e5-948e-6ed78251a102.png)

**Comment by romoore** [comment] 2018-02-16 14:55
This is seen in Apple's headers as well and appears to be an Xcode text parsing issue.  See MFMailComposeViewController.h for an example.

Apple's own [article on adding links to header documentation](https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/Links.html#//apple_ref/doc/uid/TP40016497-CH18-SW1) uses this same format. I think this issue should be closed as Working as Intended for MDC-iOS.

**Closed by romoore** 2018-02-16 14:55 UTC
Labels: Triaged, is:fixit, type:Documentation
