### ISSUE TITLE
InkView in MDCTabBar items is above title/image

### ISSUE THREAD

**Issue by garrettmurray** [material-components/material-components-ios#1480] opened 2017-06-02 19:57 UTC
### Overview
The InkView for an MDCItemBarCell is on top of everything in the item. This means if you use a dark inkView, you will cover the contents of your tab which is undesirable.

Gif of the issue: http://d.pr/i/CyJ31z

### Reproduction steps

Implement an MDCTabBar, set the inkColor to something dark (.black) and the tintColor to something light (.white). When touching a tab item, the inkColor will cover the icon.

### Version number
23.4.1

### Operating system and device
iOS 9/10

**Comment by ajsecord** [comment] 2017-06-02 20:04
Thanks! My first reaction was that this was working as intended, but I think you are correct. We should check with design on our side to make sure.

**Comment by garrettmurray** [comment] 2017-06-02 20:06
@ajsecord That was my thought at first too, because in most cases inkColor tends to be light and it covering items has no visual impact. But since inkColor can technically be anything, it becomes a problem if it's dark.

**Comment by ajsecord** [comment] 2017-06-02 20:10
We'll check it out and comment here, then figure out what to do next. Should be an easy fix?

**Comment by ajsecord** [comment] 2017-06-02 20:57
Verified—the ink should be behind the icon and the text.

**Comment by romoore** [comment] 2017-06-29 13:46
This was merged too quickly.  We got input from a designer and the `inkLayer` needs to remain above the content.  I found some [Ink color examples](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) may be helpful in selecting complementary color schemes for components.

**Closed** 2017-06-29 14:48 UTC
Labels: type:Visual bug, where:TabBar
