### ISSUE TITLE
Support to Swift Package!!

### ISSUE THREAD

**Issue by dverdugo85** [material-components/material-components-ios#9457] opened 2020-01-21 03:22 UTC
## Additional context

its more simple to incorporate inside project with swift package!! regards!!

---
#### Internal data
- Associated internal bug: [b/148271232](http://b/148271232)

**Comment by codeman7** [comment] 2020-06-26 15:12
This is a duplicate of #7559

**Closed by codeman7** 2020-06-26 15:12 UTC
Labels: skill:Swift, type:Feature request
