### ISSUE TITLE
[iOS11 only] MDCButton should truncate its label instead of shrinking its image

### ISSUE THREAD

**Issue by yzhang2018** [material-components/material-components-ios#2501] opened 2017-11-21 21:51 UTC
### Overview
This bug only happens on iOS11. 

The bug is that MDCFlatButton will shrink its image to make more space for its label, instead of truncating the label's text. When the label has a really long text, the image will have a 0 width so the image becomes invisible and the label takes up the button's whole width.

I've tried to reproduce this bug with a UIButton, but it works fine on iOS11. So I suspect this might be a MDCButton bug. 

 - Screenshots/Video (if possible)
![bug1](https://user-images.githubusercontent.com/33880483/33098627-eb4930e8-cec2-11e7-98a8-3ad3eb8b8cd3.PNG)
![bug2](https://user-images.githubusercontent.com/33880483/33098628-eb5aee28-cec2-11e7-8454-fadeedcd3d71.PNG)
![bug3](https://user-images.githubusercontent.com/33880483/33098629-eb721f94-cec2-11e7-8a77-767a8cdf3881.png)

### Version number
 - Found in CHANGELOG.md

### Operating system and device
iOS 11, iPhone7+, iPhone7

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by romoore** [comment] 2017-11-22 04:47
Hi @yzhang2018, glad to see you're using MDC-iOS. 😀  Sorry to hear about your difficulty with buttons. 😞 

I took a look at this and am able to reproduce the issue with UIButton. I don't see any difference in behavior between MDCFlatButton and UIButton.  You are correct that UIButton has changed its layout behavior between iOS 10 and iOS 11 and now seems to favor the title over the image if both are set.

The core issue seems to be the width constraint: if you force a width less than the intrinsic content size of the button, UIButton is shrinking the imageView instead of truncating the text.  I am going to close this issue because I believe it is not an MDC bug. *Please reopen it if I've missed anything.*

## iPhone 5s/iOS 9.3 (Simulator)
MDC on the left, UIButton on the right. For both MDCFlatButton and UIButton, the image remains perfectly rendered and the title is truncated and eventually removed.

![iphone5s-ios9 3](https://user-images.githubusercontent.com/1753199/33108902-a2a17e14-cf0c-11e7-9d9a-55e90a1a1424.png)

## iPhone 5s/iOS 11.0 (Simulator)
MDC on the left, UIButton on the right. For both MDCFlatButton and UIButton, the image is horizontally compressed and eventually removed while the title takes up more and more space.

![iphone5s-ios11](https://user-images.githubusercontent.com/1753199/33108949-db7411fc-cf0c-11e7-8c79-7ed8f7b78678.png)

## Test project
1. Create new Single View Application project in Xcode
1. In the project directory, run `pod init`
1. Update the Podfile to add `pod MaterialComponents` to the project
1. Run `pod install`
1. Open the generated workspace in Xcode
1. Create a storyboard with 6 buttons - 3 MDCFlatButton, 3 UIButton
1. Set constraints to position all buttons.
1. Leave 2 buttons (one MDC, one UI) without width constraints
1. Set width constraints on other buttons
1. Set various labels/images

[flatbuttontest.zip](https://github.com/material-components/material-components-ios/files/1494574/flatbuttontest.zip)

## Getting back to pre-iOS 11 behavior
I think your best bet would be trying to do one of two things:
* Truncate your text so that it doesn't go beyond a character count or point size.
* Change your layout to a `UIImageView` with a multiline `UILabel` adjacent to it. Cover these with an "invisible" MDCFlatButton. It seems a little bit inelegant to me, but I understand [it was not uncommon many years ago](https://www.youtube.com/watch?v=hlWMN5h6aH4). 

If those aren't possible, you could do some manual "adjustment" of the `imageView` and `titleLabel` in the VC. The only way I was able to get the imageView to be fully-sized and get the title to truncate (just like iOS 9/10), was to manually manipulate the views after layout. **I do not recommend taking this approach,** but it does seem to work for very simple layouts.  Here is some very basic code that I used that was enough to demonstrate the approach.

```objectivec
// Does not handle RTL, imageEdgeInsets, titleEdgeInsets, many other things.
- (void)forceButtonImageToFullSize:(UIButton *)button {
  CGFloat width = CGRectGetWidth(button.imageView.bounds);
  CGFloat imageWidth = button.imageView.image.size.width;
  CGFloat resizeAmount = imageWidth - width;
  CGPoint imageCenter = button.imageView.center;
  CGPoint titleCenter = button.titleLabel.center;
  button.titleLabel.bounds =
  CGRectMake(CGRectGetMinX(button.titleLabel.bounds),
             CGRectGetMinY(button.titleLabel.bounds),
             CGRectGetWidth(button.titleLabel.bounds) - resizeAmount,
             CGRectGetHeight(button.titleLabel.bounds));
  button.titleLabel.center = CGPointMake(titleCenter.x + (resizeAmount / 2),
                                               titleCenter.y);
  button.imageView.bounds =
  CGRectMake(CGRectGetMinX(button.imageView.bounds),
             CGRectGetMinY(button.imageView.bounds),
             CGRectGetWidth(button.imageView.bounds) + resizeAmount,
             CGRectGetHeight(button.imageView.bounds));
  button.imageView.center = CGPointMake(imageCenter.x + (resizeAmount / 2),
                                              imageCenter.y);
}
```

The end result, at least for my static view, was very similar to iOS 9. The "adjusted" button is the one in the bottom-left. 
![iphone5s-ios11-hacked](https://user-images.githubusercontent.com/1753199/33110388-75553762-cf15-11e7-9a5b-4df9cf2f3057.png)

**Closed** 2017-11-22 04:47 UTC
Labels: type:Visual bug, version:iOS11, where:Buttons

**Comment by romoore** [comment] 2017-11-30 13:59
As a follow-up to this issue, I discovered that `MDCButton` and `UIButton` still behave the same, but the "image-squashing" behavior that is observed can be reproduced by having a constraint to align the baselines of two buttons. This is the case in my sample project. If the baseline constraints are removed, then the image is displayed fully in both `MDCButton` and `UIButton`.
