### ISSUE TITLE
AppBar Covering top of scrollview after rotation

### ISSUE THREAD

**Issue by bosbefok** [material-components/material-components-ios#2156] opened 2017-10-11 23:26 UTC
### Overview
I've managed to repro what appears to be #2151 or a related issue outside of the Catalog app. It is affecting all ScrollViews tracked by MDCAppBar on all devices iOS 11.

### Example project
https://github.com/despisedIcon/AppBarBugExample

![simulator screen shot - iphone x - 2017-10-12 at 09 07 50](https://user-images.githubusercontent.com/7425648/31471593-dbd69dd6-af2c-11e7-9477-4057887357ab.png)![simulator screen shot - iphone x - 2017-10-12 at 09 07 54](https://user-images.githubusercontent.com/7425648/31471596-de00c79e-af2c-11e7-9998-b3946dc1d7e2.png)

### Reproduction steps
 - Download example project
 - Set simulator to landscape
 - Launch project
 - Rotate simulator 90deg CW to portrait

### Version number
 - 35.3.0

### Operating system and device
 - iOS 11
 - iPhone 6,7,8,X

### Related issues
 - #2151 #2069

**Comment by garrettmurray** [comment] 2017-10-12 21:38
We can also reproduce this outside of catalog, in our app Science Journal. Even after upgrading to 36.0.0. If we enter a view in landscape and then rotate to portrait, the scroll view is up under the app bar permanently.

**Comment by chuga** [comment] 2017-10-12 22:57
Yup, you're right. This is a separate issue. Looking into it.

**Comment by chuga** [comment] 2017-10-13 01:56
I have a fix for this that I’ll be testing tomorrow to make sure I don’t
cause any regressions.

**Closed** 2017-10-16 15:53 UTC

**Comment by garrettmurray** [comment] 2017-10-24 19:15
This is still not fixed in 37.0.0 and in fact is worse. Now scroll views have extra padding on top on initial load (this did not happen before) and then still exhibit the cutoff after rotation changes.

Initial load of this VC shows extra space at the top of the scroll view:
![simulator screen shot - iphone 8 plus - 2017-10-24 at 12 13 16](https://user-images.githubusercontent.com/6025/31963202-c09bd3e2-b8b4-11e7-8c81-b18f17d70878.png)

Rotating to landscape shows the scroll view is up under the app bar as before, and cannot be scrolled to 0,0.
![simulator screen shot - iphone 8 plus - 2017-10-24 at 12 13 21](https://user-images.githubusercontent.com/6025/31963214-ce9facca-b8b4-11e7-816c-01a1fd5a5871.png)

Prior to this release, the problem was different:
1. No initial scroll issue.
2. After rotating to landscape, no scroll issue.
3. After rotating back to portrait, issue.

Now we're seeing issues in every state.

**Comment by chuga** [comment] 2017-10-24 19:19
I'm sorry to hear that. Can you double check that you're tracking the scroll view in the flexible header, and that all of its events are being propagated correctly?
Also, what iOS version(s) and device(s) is this happening on?

**Comment by chuga** [comment] 2017-10-24 20:47
FWIW, the original bug described in this issue has been fixed. I just tested the demo project provided in this issue with the latest version of MDC, and now the content is being pushed down properly. I did notice that on rotation we're for some reason accounting for the safe area twice (so the header is bigger than what it should be) so I'm looking into that.

If after verifying that you're indeed tracking the scroll view correctly (and that the scrolling events are also being propagated correctly) the issue persist, can you provide us a demo project that shows the bug you're experiencing so that we can look into it?

**Comment by garrettmurray** [comment] 2017-10-24 21:04
@chuga Yep, you're right—we have a bug in our logic for iPhone X that was causing the extra gap at the top, but the other issue is that there was a regression in 37.0 that is making the App Bar in landscape too tall again. Thanks.

**Comment by chuga** [comment] 2017-10-24 21:13
On landscape? Are you by any chance explicitly setting the min/max height of the flexible header? If you are, you should subtract the previously hardcoded 20pts for the status bar, and set minMaxHeightIncludesSafeArea to false. Let me know if that fixes that issue you're seeing.

**Comment by garrettmurray** [comment] 2017-10-24 21:28
Landscape, yes. We are not setting min/max height of the header at all. This issue was resolved in 36 but is back in 37.

**Comment by chuga** [comment] 2017-10-24 21:36
Ok, would you mind opening a new bug with as much info as you can (and hopefully a way to repro)? You can assign it to me.
Thanks!
