### ISSUE TITLE
[Catalog] Dialogs/Alert Controller "Show Long Alert" overlaps top cut-out on iPhone X

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1973] opened 2017-09-13 13:38 UTC
### Overview
The "Show Long Alert" example modal view overlaps a portion of the top cut-out on the iPhone X. When the content is scrolled, the top line of text is cut-off and the status bar is partially overlapped.

![dialog-longalert-ipx](https://user-images.githubusercontent.com/1753199/30380294-31f2a6c0-98d4-11e7-89e1-71eb6c8221a5.png)

### Reproduction steps
1. Open MDC Catalog on an iPhone X &rarr; Dialogs &rarr; Alert Controller 
2. Tap on "Show Long Alert"

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

**Comment by chuga** [comment] 2017-09-19 20:00
Marking it as a duplicate of #2007

**Closed by chuga** 2017-09-19 20:00 UTC
Labels: device:iPhone X, type:Visual bug, where:Catalog
