### ISSUE TITLE
[ActionSheet] Incorrect height upward flick

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#5205] opened 2018-09-23 02:44 UTC
## Reproduction steps

1. Open up MDCDragons
2. Go to "Action Sheet (Swift)"
3. Select any option other than "Thirty Options"
4. After it opens up flick the sheet upward

## Expected behavior

The sheet height should bounce back to the same height as when it was originally opened.

## Actual behavior

The sheet height is different then when it was originally opened

## Platform

 - Device: [iPhone X]
 - OS: [iOS12.0]

## Additional context

This may be related to MDCBottomSheet.

## Videos
| Example error | Exaggerated example error |
| ------ | ------ |
|![Example video](https://user-images.githubusercontent.com/7131294/45923525-e039a680-beb6-11e8-80b7-cd42bcdf910b.gif)|![y](https://user-images.githubusercontent.com/7131294/45923600-994cb080-beb8-11e8-80c9-84f381fabea6.gif)|

**Comment by codeman7** [comment] 2018-09-23 02:49
It has to do with the safe area.

**Comment by codeman7** [comment] 2018-09-23 02:58
I believe the error is in MDCBottomSheetContainerView.

**Comment by material-mirror** [comment] 2018-10-04 22:28
The internal issue is now closed, closing this issue.

**Closed by material-mirror** 2018-10-04 22:28 UTC
Labels: Internal, [ActionSheet], [BottomSheet], type:Bug

**Comment by jverkoey** [comment] 2018-10-04 22:30
This is a duplicate of https://github.com/material-components/material-components-ios/issues/5330
