### ISSUE TITLE
[Catalog] "Start Demo" button cut-off when more than 2 lines of component text.

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4467] opened 2018-07-02 18:31 UTC
The Buttons component has no primary example.

![simulator screen shot - iphone 4s - 2018-07-02 at 14 30 27](https://user-images.githubusercontent.com/1753199/42180245-849938ce-7e04-11e8-9b29-f91046c30b82.png)

![simulator screen shot - iphone 4s - 2018-07-03 at 09 42 53](https://user-images.githubusercontent.com/1753199/42223343-8dfca198-7ea5-11e8-9689-ace82483515b.png)

![simulator screen shot - iphone 4s - 2018-07-03 at 09 50 57](https://user-images.githubusercontent.com/1753199/42223788-9b1ab4d6-7ea6-11e8-9d19-b31dcc5bbe10.png)

## Reproduction steps
1. Launch the catalog
1. Open "Buttons"

## Expected behavior
A primary example is shown with the "Start Demo" button.

## Actual behavior
No such button/example are available.

## Platform (please complete the following information)
iPhone 4s/iOS 9 (Simulator)

**Comment by jverkoey** [comment] 2018-07-17 17:53
Duplicate of https://github.com/material-components/material-components-ios/issues/4572.

**Closed by jverkoey** 2018-07-17 17:53 UTC
Labels: Needs actionability review, [Catalog], type:Bug
