### ISSUE TITLE
Unexpected flexible header view resizing when using together with a paged view

### ISSUE THREAD

**Issue by mikemeko** [material-components/material-components-ios#235] opened 2016-03-28 22:01 UTC
We have a setup in which we a custom flexible header view on top of a paged view containing scroll view pages.

An unexpected behavior we see is that when turning the page on the paged view, the header shrinks to minimum size, then grows back to maximum size (animated). The expected behavior (I think) is that the header would stay at the same size with no change.

Demo attached.

@jmig
@jverkoey

[HeaderBehaviorWithPageView.zip](https://github.com/google/material-components-ios/files/192542/HeaderBehaviorWithPageView.zip)

**Comment by jverkoey** [comment] 2018-08-24 02:00
Duplicate of https://github.com/material-components/material-components-ios/issues/3130

**Closed by jverkoey** 2018-08-24 02:00 UTC
Labels: Needs actionability review, Needs research, [FlexibleHeader], fixit, type:Bug

**Comment by romoore** [comment] 2018-08-24 02:02
I'm surprised that #3130 isn't marked a duplicate of this one...

**Comment by jverkoey** [comment] 2018-08-24 02:05
#3130 has more details overall.
