### ISSUE TITLE
[AppBar] Incorrectly setting tracked scrollView top inset

### ISSUE THREAD

**Issue by despisedIcon** [material-components/material-components-ios#2151] opened 2017-10-11 13:43 UTC
### Overview
The top content inset of a tracked scrollview is incorrectly being set after landscape -> portrait rotation. 100% repro.

Issue is not present portrait -> landscape. 
iOS 11 iPhone X only.

![simulator screen shot - iphone x - 2017-10-11 at 23 30 43](https://user-images.githubusercontent.com/7425648/31443563-1fa84c44-aedd-11e7-8a2f-b9e2fe9abacf.png)
![simulator screen shot - iphone x - 2017-10-11 at 23 30 49](https://user-images.githubusercontent.com/7425648/31443570-20698a94-aedd-11e7-86ca-0a9f1409286c.png)
![simulator screen shot - iphone x - 2017-10-11 at 23 30 57](https://user-images.githubusercontent.com/7425648/31443578-28335520-aedd-11e7-883a-fdfdd7964620.png)

### Reproduction steps
 - Launch MDC Catalog with iPhone X
 - Rotate simulator 90deg CCW to landscape
 - Select any of the MDC component tiles
 - Rotate simulator 90deg CW to portrait

### Version number
 - 35.3.0

### Operating system and device
 - iOS 11
 - iPhone X

**Comment by chuga** [comment] 2017-10-11 15:18
Thanks for reporting! This is an issue in the Catalog itself, and not in the App Bar. Since we already have an open bug for it, I'll close this one.

Duplicate of https://github.com/material-components/material-components-ios/issues/2069

**Closed by chuga** 2017-10-11 15:18 UTC

**Comment by despisedIcon** [comment] 2017-10-11 23:09
I've managed to repro what appears to be this or a related issue outside of the Catalog app. It is affecting all ScrollViews tracked by MDCAppBar on all devices iOS 11.

Uploaded example project for you to see.

### Reproduction steps
 - Set simulator to landscape
 - Launch project
 - Rotate simulator 90deg CW to portrait

https://github.com/despisedIcon/AppBarBugExample

In the example you can see MDCFlexibleHeaderViewController is unaffected and content top is set correctly.

![simulator screen shot - iphone x - 2017-10-12 at 09 07 50](https://user-images.githubusercontent.com/7425648/31471593-dbd69dd6-af2c-11e7-9477-4057887357ab.png)![simulator screen shot - iphone x - 2017-10-12 at 09 07 54](https://user-images.githubusercontent.com/7425648/31471596-de00c79e-af2c-11e7-9998-b3946dc1d7e2.png)
