### ISSUE TITLE
[Tabs] selectionIndicatorTemplate should be weak

### ISSUE THREAD

**Issue by IchordeDionysos** [material-components/material-components-ios#5206] opened 2018-09-23 22:52 UTC
When setting selectionIndicatorTemplate this causes my view controller to not deallocate correctly ...

## Reproduction steps

1. Implement a Tabbar the standard way
2. Make you View Controller conform to `MDCTabBarIndicatorTemplate`
3. Set `tabBar.selectionIndicatorTemplate = self` where `self` is the ViewController

## Expected behavior

The view controller deallocates correctly when calling. `self.dismiss()`

## Actual behavior

The TabBar prevents the ViewController to deallocate, as `selectionIndicatorTemplate` is not weak.

## Platform (please complete the following information)

 - Device: iPhoneX
 - OS: iOS 12.0

## Additional context

https://github.com/material-components/material-components-ios/blob/21810842725b86f68fb7dcbd023e4c39c56e3a08/components/Tabs/src/MDCTabBar.h#L164

---
#### Internal data
- Associated internal bug: [b/117134507](http://b/117134507)

**Comment by andrewoverton** [comment] 2018-09-24 16:51
Thank you for filing this issue! While we decide how best to address it you could consider using an object other than your view controller as the `MDCTabBarIndicatorTemplate`, like we do in the [`TabBarIndicatorTemplateExample`](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/examples/TabBarIndicatorTemplateExample.swift#L81)

**Comment by romoore** [comment] 2019-05-24 16:45
Closing this as "works as intended." The Template is documented as using `strong` retain semantics, so clients should be sure not to introduce retain cycles with properties like this.  In general, if the view were to use a `weak` property to retain its indicator, it's likely that many clients would quickly deallocate their templates.  The view should own the template, and as @andrewoverton mentioned, the template should be an object that's not also the view controller.

**Closed by romoore** 2019-05-24 16:45 UTC
Labels: [Tabs], type:Bug
