### ISSUE TITLE
[MDCActivityIndicator] Interface Builder - Failed to Render and update autolayout status

### ISSUE THREAD

**Issue by joelyoungblood** [material-components/material-components-ios#1556] opened 2017-06-22 23:53 UTC
### Overview
When using Interface Builder to add an MDCActivityIndicator to a view, I got the following error:

<img width="617" alt="screen shot 2017-06-21 at 8 24 18 pm" src="https://user-images.githubusercontent.com/11529627/27460722-d14ffe08-5783-11e7-987e-b0ffb1bd5927.png">

This was with Xcode 8.3.3 (8E3004b), but out of curiosity (and a general mistrust of IB) decided to try it with Xcode 9.0 beta 2 (9M137d) and got the same error:

<img width="513" alt="screen shot 2017-06-22 at 7 44 25 pm" src="https://user-images.githubusercontent.com/11529627/27460780-13fb2a48-5784-11e7-985a-d2ec6a5cdbca.png">

### Reproduction steps
- Both projects used Cocoapods. After the error's showed up the usual song and dance of clean, rebuild, see if error remains was followed.

### Version number
 - 23.4.1

---
#### Internal data
- Associated internal bug: [b/117179267](http://b/117179267)

**Comment by primax79** [comment] 2017-10-02 14:10
the problem is still present in Xcode 9 stable

**Comment by bleeckerj** [comment] 2017-12-15 03:57
I'm experiencing the same problem in Xcode 9.2 (9C40b). Project builds successfully, but the error remains.

**Comment by material-mirror** [comment] 2019-07-30 16:55
The internal issue [b/117179267](http://b/117179267) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 16:55 UTC
Labels: [ActivityIndicator], skill:Interface Builder, type:Bug
