### ISSUE TITLE
[Dialogs] Implement MDCActionSheetController

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2791] opened 2018-01-03 17:27 UTC
Similar to the MDCAlertController implementation.

https://material.io/guidelines/components/bottom-sheets.html#

**Comment by jverkoey** [comment] 2018-08-27 13:06
Duplicate of https://github.com/material-components/material-components-ios/issues/4663.

**Closed by jverkoey** 2018-08-27 13:06 UTC
Labels: [ActionSheet], skill:API design, type:Feature request
