### ISSUE TITLE
[TextFields] Floating label sizing issues

### ISSUE THREAD

**Issue by intiocean** [material-components/material-components-ios#4471] opened 2018-07-03 09:26 UTC
I have an `MDCTextField` with a large font (`MDCTypography.display3Font()`) the floating label size jumps between a smaller and larger font size as soon as the first character is entered into the text field. Furthermore, if you just click into and then out of the text field without entering text the label stays floating and doesn't go back to it's initial state.

## Reproduction steps
Here is my code to setup the text field: 
```swift
    let valueTextField: MDCTextField = {
        let value = MDCTextField()
        value.translatesAutoresizingMaskIntoConstraints = false
        return value
    }()

    override func viewDidLoad() {
        valueTextField.font = MDCTypography.display3Font()
        valueTextField.alpha = MDCTypography.titleFontOpacity()
        valueTextField.keyboardType = .numberPad
        let valueController = MDCTextInputControllerUnderline(textInput: valueTextField)
    }
```
I then add the `valueTextField` to a `UIStackView`

## Expected behavior

Ideally the text should be larger and when the label is in as the placeholder for the text field it is also larger but then it would float up and shrink to the same size as the other labels do (on the `MDCTextField`s that haven't had their font size changed.

## Actual behavior
Both behaviours described shown in gif:
![img_3296](https://user-images.githubusercontent.com/725843/42211413-73f0fc12-7eab-11e8-8063-b21c0d39c1cc.gif)

## Platform (please complete the following information)

 - Device: iPhone 8
 - OS: iOS 11.4

**Comment by TYRONEMICHAEL** [comment] 2018-07-28 15:59
+ 1

I suspect the following is the issue in MDCTextInputCommonFundament:

```
- (void)didSetFont {
  UIFont *font = self.textInput.font;
  self.placeholderLabel.font = font;

  [self updatePlaceholderPosition];
}
```

**Comment by willlarche** [comment] 2018-09-25 16:09
I think the issue is that you're setting a font on the text field but the controller is made to override it. You see the same issue in our custom fonts example in MDCDragons (#5233). And you can see another example in #4189.

Fonts should be set on the controller now, not the text field, with `inlinePlaceholderFont` and `textInputFont`. 

```
    override func viewDidLoad() {
        valueTextField.keyboardType = .numberPad
        let valueController = MDCTextInputControllerUnderline(textInput: valueTextField)
        valueController.inlinePlaceholderFont = MDCTypography.display3Font()
        valueController.textInputFont = MDCTypography.display3Font()
    }
```

BTW: What's ur desired behavior with `valueTextField.alpha = MDCTypography.titleFontOpacity()`?

**Comment by willlarche** [comment] 2018-09-25 16:09
Duplicate of #4189

**Closed by willlarche** 2018-09-25 16:09 UTC
Labels: [TextFields], skill:UIFont, type:Bug

**Comment by intiocean** [comment] 2018-10-17 16:30
Fantastic - You are indeed correct @willlarche. Thanks for the help!
