### ISSUE TITLE
[TextFields] TextFieldSwiftExample has unsatisfiable constraints on iPhone 5/iOS 10.3 Simulator

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1729] opened 2017-08-03 16:52 UTC
### Overview
```
2017-08-03 12:50:46.634914-0400 MDCCatalog[55801:1509311] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x81a4bb20 H:[UIScrollView:0x7d450e00]-(0)-|   (active, names: '|':UIView:0x81a77ae0 )>",
    "<NSLayoutConstraint:0x7d87fff0 MDCTextField:0x7d444400.trailing == UIView:0x81a77ae0.trailingMargin   (active)>",
    "<NSLayoutConstraint:0x7d897cf0 H:[MDCTextField:0x7d444400]-(0)-|   (active, names: '|':UIScrollView:0x7d450e00 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7d897cf0 H:[MDCTextField:0x7d444400]-(0)-|   (active, names: '|':UIScrollView:0x7d450e00 )>
```

### Reproduction steps
**With the device set to a Right-to-Left language**, open the TextFieldSwiftExample example in the Text Fields catalog.

### Version number
29.0.0

### Operating system and device
iPhone 5 (Simulator)/iOS 10.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179253](http://b/117179253)

**Comment by willlarche** [comment] 2017-08-03 17:09
Unable to reproduce in iPhone 5 simulator (10.3.1 and 9.0) and Xcode 9.0 beta 4. Please supply details on what was different for you.

**Comment by romoore** [comment] 2017-08-03 18:30
Sorry, it seems to only happen in Right-to-Left languages.  Updating the summary to match.

**Comment by material-mirror** [comment] 2019-07-30 16:55
The internal issue [b/117179253](http://b/117179253) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 16:55 UTC
Labels: [TextFields], app:Catalog, skill:Auto Layout, type:Bug
