### ISSUE TITLE
[BottomSheet] Crash on rotation

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3011] opened 2018-02-27 20:53 UTC
Open the following
Catalog -> BottomSheet -> Preferred Layout -> Present Sheet
Rotate the phone between landscape and portrait and a crash should happen.

iPhone 8 Sim @ 11.2

2018-02-27 15:42:24.668173-0500 MDCCatalog[17567:158477] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid size {0, 817} for item <MDCDraggableView: 0x7f971131e540; frame = (0 467; 0 817); autoresize = W+TM; gestureRecognizers = <NSArray: 0x600000252ae0>; animations = { position=<CABasicAnimation: 0x608000238c00>; bounds.origin=<CABasicAnimation: 0x6080002371c0>; bounds.size=<CABasicAnimation: 0x60800022f560>; position-2=<CABasicAnimation: 0x604000232220>; bounds.origin-2=<CABasicAnimation: 0x6040002342c0>; bounds.size-2=<CABasicAnimation: 0x604000233120>; }; layer = <CALayer: 0x600000231fa0>> in Dynamics'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010589b12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000104f2ff41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001058a02f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001049d0d69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x00000001074b4a0b -[UIDynamicAnimator _registerBodyForItem:] + 758
	5   UIKit                               0x0000000106950bf5 -[UIAttachmentBehavior _associate] + 149
	6   UIKit                               0x00000001074b1760 -[UIDynamicAnimator _registerBehavior:] + 315
	7   UIKit                               0x00000001074b7950 -[UIDynamicBehavior _associate] + 336
	8   UIKit                               0x00000001074b1760 -[UIDynamicAnimator _registerBehavior:] + 315
	9   UIKit                               0x00000001074b1513 -[UIDynamicAnimator addBehavior:] + 118
	10  MaterialComponents                  0x00000001041f1009 -[MDCSheetContainerView animatePaneWithInitialVelocity:] + 665
	11  MaterialComponents                  0x00000001041ef787 -[MDCSheetContainerView traitCollectionDidChange:] + 359
	12  UIKit                               0x0000000106770caa -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 163
	13  UIKit                               0x0000000106770da6 -[UIView _wrappedProcessTraitCollectionDidChange:forceNotification:] + 415
	14  UIKit                               0x0000000106770fc2 -[UIView _processDidChangeRecursivelyFromOldTraits:toCurrentTraits:forceNotification:] + 151
	15  UIKit                               0x000000010679c9fe -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1328
	16  QuartzCore                          0x000000010650561c -[CALayer layoutSublayers] + 159
	17  QuartzCore                          0x00000001065097ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	18  QuartzCore                          0x0000000106505553 -[CALayer layoutIfNeeded] + 177
	19  UIKit                               0x00000001068951bc -[UIViewController window:willAnimateRotationToInterfaceOrientation:duration:newSize:] + 339
	20  UIKit                               0x000000010689ca90 __95-[UIViewController(AdaptiveSizing) _window:viewWillTransitionToSize:withTransitionCoordinator:]_block_invoke.3607 + 54
	21  UIKit                               0x000000010743d811 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
	22  UIKit                               0x000000010743965a -[_UIViewControllerTransitionContext __runAlongsideAnimations] + 193
	23  UIKit                               0x000000010678f630 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 560
	24  UIKit                               0x000000010678fb0d +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 99
	25  UIKit                               0x0000000106e62a43 __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2 + 304
	26  UIKit                               0x0000000106794271 +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:] + 188
	27  UIKit                               0x0000000106e627dc __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke + 136
	28  UIKit                               0x000000010678f630 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 560
	29  UIKit                               0x000000010678fb0d +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 99
	30  UIKit                               0x0000000106e626c2 -[_UIWindowRotationAnimationController animateTransition:] + 513
	31  UIKit                               0x0000000106747666 -[UIWindow _rotateToBounds:withAnimator:transitionContext:] + 601
	32  UIKit                               0x000000010674a38e -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] + 1859
	33  UIKit                               0x000000010674adc4 -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] + 709
	34  UIKit                               0x0000000106749b8a -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 123
	35  UIKit                               0x00000001067486ec __57-[UIWindow _updateToInterfaceOrientation:duration:force:]_block_invoke + 112
	36  UIKit                               0x000000010674857a -[UIWindow _updateToInterfaceOrientation:duration:force:] + 485
	37  CoreFoundation                      0x0000000105836eac __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	38  CoreFoundation                      0x0000000105836daa _CFXRegistrationPost + 442
	39  CoreFoundation                      0x0000000105836af2 ___CFXNotificationPost_block_invoke + 50
	40  CoreFoundation                      0x00000001057f8792 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	41  CoreFoundation                      0x00000001057f790c _CFXNotificationPost + 652
	42  Foundation                          0x000000010490e8f2 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	43  UIKit                               0x0000000106ad29a1 -[UIDevice setOrientation:animated:] + 290
	44  UIKit                               0x0000000107187683 __124-[_UICanvasDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:canvas:transitionContext:]_block_invoke + 85
	45  UIKit                               0x00000001072edd78 _performChangesWithTransitionContext + 613
	46  UIKit                               0x00000001071875fc -[_UICanvasDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:canvas:transitionContext:] + 250
	47  UIKit                               0x000000010718748f __133-[_UICanvasDeviceOrientationSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 112
	48  UIKit                               0x00000001072edb06 _performActionsWithDelayForTransitionContext + 100
	49  UIKit                               0x00000001071873db -[_UICanvasDeviceOrientationSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 173
	50  UIKit                               0x0000000106e68b25 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	51  UIKit                               0x0000000106ca3b06 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 509
	52  FrontBoardServices                  0x000000010b537723 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 205
	53  libdispatch.dylib                   0x000000010a79533d _dispatch_client_callout + 8
	54  libdispatch.dylib                   0x000000010a79a9f3 _dispatch_block_invoke_direct + 592
	55  FrontBoardServices                  0x000000010b56b498 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	56  FrontBoardServices                  0x000000010b56b14e -[FBSSerialQueue _performNext] + 464
	57  FrontBoardServices                  0x000000010b56b6bd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	58  CoreFoundation                      0x000000010583e101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	59  CoreFoundation                      0x00000001058ddf71 __CFRunLoopDoSource0 + 81
	60  CoreFoundation                      0x0000000105822a19 __CFRunLoopDoSources0 + 185
	61  CoreFoundation                      0x0000000105821fff __CFRunLoopRun + 1279
	62  CoreFoundation                      0x0000000105821889 CFRunLoopRunSpecific + 409
	63  GraphicsServices                    0x000000010bdff9c6 GSEventRunModal + 62
	64  UIKit                               0x00000001066cb5d6 UIApplicationMain + 159
	65  MDCCatalog                          0x0000000103ce78b7 main + 55
	66  libdyld.dylib                       0x000000010a811d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Internal bug: cl/73949340

**Comment by codeman7** [comment] 2018-08-16 14:57
Within Catalog I couldn't find a 'Preferred Layout' example and within dragons I can only find 'Preferred content size'. On the 'Preferred content size' example I couldn't reproduce this bug, possibly it was closed in a commit that doesn't link to the issue.

**Comment by jverkoey** [comment] 2018-08-27 13:11
Closing as not reproducible.

**Closed by jverkoey** 2018-08-27 13:11 UTC
Labels: Crasher, Not reproducible, [BottomSheet], type:Bug
