### ISSUE TITLE
[Snackbar] Flashes on dismiss

### ISSUE THREAD

**Issue by liquidx** [material-components/material-components-ios#1091] opened 2016-12-16 02:42 UTC
The snackbar dismisses with a downward animation, but flashes visibly for a split second before disappearing. Note that this only appears on the device and not in the simulator.

### Reproduction steps
You can observe this in the MDCCatalog app in the Snackbar example.

### Version number
Branch: develop at 0343c9d 

### Operating system and device
Xcode: 8.2
Device: iPhone SE

**Comment by liquidx** [comment] 2016-12-16 02:44
![2016-12-15 21_44_31](https://cloud.githubusercontent.com/assets/72062/21249962/af0e8e76-c30f-11e6-9ab7-48fd4e3dc50d.gif)

**Comment by Arcank** [comment] 2016-12-16 10:20
Duplicate of #1018.

**Closed by Arcank** 2016-12-16 10:20 UTC
Labels: type:Visual bug
