### ISSUE TITLE
[Buttons] Ink on button touch reflects 'old' frame

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#754] opened 2016-10-13 18:36 UTC
### Overview of the issue

When a button needs to change shape at the same moment it shows ink, the ink respects the old size.
### Reproduction steps

Add an MDCRaisedButton that has either constraints or masks allowing it to expand width.
Set its action to be a function that extends the title of the button with each call.
The title will continue to push the button's sides apart but the ink will stop at the smaller older frame.

See attachment.
[Raised Button Ink.zip](https://github.com/google/material-components-ios/files/527882/Raised.Button.Ink.zip)
### Motivation and context

To the eye, the frame changes first and then the ink begins (since the ink is gradual and the frame is instant.)

**Comment by romoore** [comment] 2017-06-22 19:48
Also affects MDCFlatButton

**Comment by jverkoey** [comment] 2018-08-24 02:46
Duplicate of https://github.com/material-components/material-components-ios/issues/3056.

**Closed by jverkoey** 2018-08-24 02:46 UTC
Labels: [Ink], type:Bug
