### ISSUE TITLE
MaterialComponentsBeta in example

### ISSUE THREAD

**Issue by beraybentesen** [material-components/material-components-ios#6610] opened 2019-02-12 21:40 UTC
MDCBottomNavigationBarController example is not available through the pod library.

---
#### Internal data
- Associated internal bug: [b/124384457](http://b/124384457)

**Comment by randallli** [comment] 2019-02-13 19:38
@romoore do we have a tracking bug for moving it to the beta podspec?

**Comment by romoore** [comment] 2019-02-13 19:40
It is beta already - this issue is that it's not in the published Podspec (Ready).

https://github.com/material-components/material-components-ios/blob/develop/MaterialComponentsBeta.podspec#L53

**Comment by romoore** [comment] 2019-03-27 19:20
Closing as intended behavior.

**Closed by romoore** 2019-03-27 19:20 UTC
Labels: [BottomNavigation], skill:CocoaPods, type:Feature request
