### ISSUE TITLE
[FeatureHighlight][VoiceOver] Announce that a feature highlight has been presented

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#2677] opened 2017-12-11 11:23 UTC
There is no context given to a user with VO turned on. If a user enters a screen with a feature highlight, there is no indication that a view is temporary and can be dismissed.`MDCFeatureHighlightViewController` should announce that there a feature highlighted.

**Comment by ianegordon** [comment] 2018-05-23 19:14
Reminder that any text send to VO will need i18n support.

**Comment by romoore** [comment] 2018-05-30 19:02
Closing as a duplicate of #4036 which has a bit more context.

**Closed by romoore** 2018-05-30 19:02 UTC
Labels: Accessibility, [FeatureHighlight], type:Bug
