### ISSUE TITLE
{Testing} Create mechanism for test fakes and test data

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6712] opened 2019-02-26 17:59 UTC
## Summary
Sets up MDC iOS to allow each component to export "Test fakes" and test data for use by other components when performing tests.  

## Background
Contributors writing tests, particularly those that use shared components like schemes, can do so more quickly by accessing test data and test fakes directly from the component rather than having to write custom objects for each test.

## Acceptance Criteria
1. Components keep test fakes and testing data in a conventions-based directory structure that's sensible and easy to guess
1. Component test code (unit, snapshot, UI, integration, etc.) can depend on the test fakes targets 
1. Can be used by non-published test specs (Beta, Snapshot tests, etc.)

---
#### Internal data
- Associated internal bug: [b/126907351](http://b/126907351)

**Comment by material-mirror** [comment] 2019-04-04 19:46
The internal issue [b/126907351](http://b/126907351) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-04-04 19:46 UTC
Labels: [testing], skill:Bazel, skill:CocoaPods, type:Internal cleanup

**Comment by andrewoverton** [comment] 2019-04-05 20:01
This issue was closed because it's a duplicate of https://github.com/material-components/material-components-ios/issues/7073
