### ISSUE TITLE
[Dialogs] MDCAction: way to ignore click

### ISSUE THREAD

**Issue by farfromrefug** [material-components/material-components-ios#9871] opened 2020-03-10 16:06 UTC
Imagine you want to prompt for a password.
You might want to ignore clicks on the OK button until a password is actually filled (though not ignoring the cancel button).

This behavior is not possible right now as the dialog is always dismissed on a button click
https://github.com/material-components/material-components-ios/blob/c2af4ae17f0feec12a1a6778dba3bb80505263c7/components/Dialogs/src/MDCAlertController.m#L457

On android this is possible because it s the dev job to actually dismiss the dialog on a button click. Which is pretty awesome because you can do whatever you want.

Could you make it possible on iOS too?

Thanks

**Comment by galiak11** [comment] 2021-03-20 11:40
This feature is now supported - as a result of fix added in https://github.com/material-components/material-components-ios/commit/9c91e26f04cd5829cb996818a6d0119b23c944fa#diff-43483459eff8f1568ef6daa1fef3414f1f56d2352bf53d6a48298de06468c38c.

Closing the issue. Feel free to reopen if the issue is not resolved.

**Closed by galiak11** 2021-03-20 11:40 UTC
Labels: [Dialogs], type:Feature request
