### ISSUE TITLE
[Buttons] VoiceOver Does Not Recognize Disabled MDCButton

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8122] opened 2019-07-30 02:15 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/137200027](http://b/137200027) for more details.

---
#### Internal data
- Associated internal bug: [b/137200027](http://b/137200027)

**Comment by jverkoey** [comment] 2019-07-30 16:58
Duplicate of https://github.com/material-components/material-components-ios/issues/8123

**Closed by jverkoey** 2019-07-30 16:58 UTC
Labels: [Buttons], skill:VoiceOver, type:Bug
