### ISSUE TITLE
[Tabs] MDCTabBarViewController should adjust the TabBar position based on the safeAreaInsets

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1977] opened 2017-09-13 15:33 UTC
### Overview
With the iPhone X affordance for the Home Screen indicator, the MDCTabBarViewController should reposition the TabBar above the Home Screen indicator.

**iPhone X**
![simulator screen shot - iphone x - 2017-09-14 at 00 13 32](https://user-images.githubusercontent.com/1753199/30385300-b93ada82-98e1-11e7-8ca8-f6a63f16d448.png)

**iPhone SE**
![simulator screen shot - iphone se - 2017-09-14 at 00 14 35](https://user-images.githubusercontent.com/1753199/30385304-bdbfbcc6-98e1-11e7-9c53-52de0e41724b.png)

### Reproduction steps
1. Open MDC Catalog on iPhone X &rarr; Tab Bar &rarr; TabBarViewController
2. Make sure the Tab Bar items in the Bar at the bottom are fully visible and not overlapping the Home Screen indicator

### Version number
34.0.2

### Operating system and device
iPhone X/iOS 11 (Simulator)

### Related issues
#1974 

---
#### Internal data
- Associated internal bug: [b/117179383](http://b/117179383)

**Comment by chuga** [comment] 2017-09-19 20:37
Marking as a duplicate of #2012

**Comment by romoore** [comment] 2017-09-19 20:46
Reopening since this issue is for the TabBar VC and #2012 is for the TabBar component itself.

**Comment by chuga** [comment] 2017-09-19 20:53
Oh, I thought fixing #2012 would fix this. Let's leave it open and see if we need to do something else.

**Comment by romoore** [comment] 2017-10-06 10:37
Also the VC should be sure to set additionalSafeAreaInsets on its child view controllers.

**Comment by material-mirror** [comment] 2019-07-30 16:55
The internal issue [b/117179383](http://b/117179383) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 16:56 UTC
Labels: [Tabs], device:iPhone X, good first issue, skill:Safe area insets, type:Bug
