### ISSUE TITLE
[MDCTextInputControllerUnderline] MDCTextInputControllerUnderline helperText length issue

### ISSUE THREAD

**Issue by paultas** [material-components/material-components-ios#6860] opened 2019-03-13 13:08 UTC
When I have an instance of MDCTextInputControllerUnderline that is used with MDCTextField and when I set MDCTextInputControllerUnderline -> helperText to a long string, it doesn't create a two line helper text, instead it creates the label and the end of the label is outside of the screen

## Expected behavior

When I set MDCTextInputControllerUnderline -> helperText  with a string that takes 2 lines on the screen, the control should display 2 lines

## Actual behavior

When I set MDCTextInputControllerUnderline -> helperText  with a string that takes 2 lines on the screen, the control displays it in just 1 line and not all the text is visible :(

## Platform (please complete the following information)

 - Device: iPhone X, iPhone 6
 - OS: iOS 12

---
#### Internal data
- Associated internal bug: [b/128528559](http://b/128528559)

**Comment by romoore** [comment] 2019-03-16 03:38
This was fixed for Outlined and Filled, but Underline is not actively supported at present. Out internal usability research has indicated that Outlined and Filled styles perform significantly better with users.

If anyone is interested in the solution, it's likely that this controller is also missing the label constraints. Adding them would prevent the label from going outside the Text Field bounds. However, support for multi-line helper/error text is more complex and is currently considered low priority.

Truncation for Filled/Outlined: https://github.com/material-components/material-components-ios/pull/6165

**Comment by romoore** [comment] 2019-03-16 03:40
Looks like this might be a duplicate of https://github.com/material-components/material-components-ios/issues/4525

**Comment by romoore** [comment] 2019-03-27 18:24
Closing as a duplicate of #4525

**Closed by romoore** 2019-03-27 18:24 UTC
Labels: [TextFields], type:Bug
