### ISSUE TITLE
Shadow Layer device rotation visual behavior is not ideal

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#307] opened 2016-04-08 19:39 UTC
We've been given reports that there are performance problems on view controllers with an MDCShadowLayer attached to a Flexible Header during device rotation.

**Comment by ianegordon** [comment] 2017-04-25 19:27
This is a case where our ShadowLayer presentation and model layer are out of sync.
Duplicate of #1287

**Closed by ianegordon** 2017-04-25 19:27 UTC
Labels: is:Needing research, Triaged, where:FlexibleHeader, where:ShadowLayer
