### ISSUE TITLE
[MDCProgressView] Add a way to add Indeterminate linear progress indicator

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#5066] opened 2018-09-08 19:09 UTC
## Feature Request/Suggestion
As per the documentation or code currently there is no way to do this. Please make this possible.

## Additional context
See Indeterminate linear progress indicator on https://material.io/design/components/progress-indicators.html#linear-progress-indicators

**Comment by andrewoverton** [comment] 2018-09-10 13:46
Thanks for filing this issue @bond- ! It seems to be a duplicate of https://github.com/material-components/material-components-ios/issues/5066, so what I'm going to do is close this one and we can eventually address that other one.

**Closed by andrewoverton** 2018-09-10 13:46 UTC
Labels: [ProgressView], type:Feature request

**Comment by bond-** [comment] 2018-09-10 13:54
@andrewoverton Did you use the wrong ticket for duplicate?

#5066 is this issue.

**Comment by andrewoverton** [comment] 2018-09-10 13:55
Yes! Fixed. Thanks @bond-
