### ISSUE TITLE
[Feature Highlight]Is there any way to make multiple feature highlight?

### ISSUE THREAD

**Issue by FritzHsiao** [material-components/material-components-ios#5562] opened 2018-10-31 03:36 UTC
I'm using feature highlight with ur demo code to make four highlight view.

   UIButton *displayedButton = [UIButton buttonWithType:UIButtonTypeSystem];
    [displayedButton addTarget:self action:@selector(nextView) forControlEvents:UIControlEventTouchUpInside];
    displayedButton.backgroundColor = [UIColor clearColor];
    displayedButton.frame = CGRectMake(_learningImage.center.x , _learningImage.center.y, _learningImage.frame.size.width, _learningImage.frame.size.height);
    
    MDCFeatureHighlightViewController *highlightController = [[MDCFeatureHighlightViewController alloc]initWithHighlightedView:_learningImage andShowView:displayedButton completion:nil];

But the HighlightedView will be complete white color, the image is missing.
nextView function from displayedButton was never fired.
I have no clue how to make this, please offer some help. 
Thanks

---
#### Internal data
- Associated internal bug: [b/118761538](http://b/118761538)

**Comment by romoore** [comment] 2018-10-31 12:50
Thanks, @FritzHsiao . Can you please post a screenshot of the incorrect behavior? 

Also, `andShowView` is expected to be a functional duplicate of the view being highlighted. It's intended for highlighting Buttons and other views that have interactions (like ripple animations) when tapped.

**Comment by material-mirror** [comment] 2019-07-30 15:51
The internal issue [b/118761538](http://b/118761538) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-07-30 15:51 UTC
Labels: [FeatureHighlight], type:Question
