### ISSUE TITLE
Internal issue: b/135017130

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7556] opened 2019-06-11 15:15 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/135017130](http://b/135017130) for more details.

---
#### Internal data
- Associated internal bug: [b/135117849](http://b/135117849)

**Comment by codeman7** [comment] 2019-06-12 17:28
This is a duplicate of #7559

**Closed by codeman7** 2019-06-12 17:28 UTC
Labels: type:Feature request
