### ISSUE TITLE
[TextFields] MDCTextField sizeToFit does not calculate width

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#2496] opened 2017-11-21 10:42 UTC
Calling `MDCTextField#sizeToFit` only sets height of the view. Width is not changed.

Version: 40.0.3.

**Comment by willlarche** [comment] 2017-11-21 16:56
Closing as duplicate of #2153 but bumping up the priority of pushing a fix.

**Closed by willlarche** 2017-11-21 16:56 UTC
Labels: type:Bug, where:TextField
