### ISSUE TITLE
[Catalog] FlexibleHeaderView Configurator example scrolls under status bar and is hard to view

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1969] opened 2017-09-13 13:18 UTC
### Overview
When turning on "Shift Behavior" using either "with status bar" or without, the content scrolls under the status bar and makes it hard to view.

***With Status Bar option***
![fh-configurator-withstatus-iphonex](https://user-images.githubusercontent.com/1753199/30378676-f4bcfb70-98ce-11e7-8990-38d284afef20.png)

***Without Status Bar option***
![fh-configurator-withoutstatus-iphonex](https://user-images.githubusercontent.com/1753199/30378711-071d83d4-98cf-11e7-9317-9e9c629b364e.png)

### Reproduction steps
 - Detailed steps to reproduce
Open MDC Catalog on iPhone X &rarr; Flexible Header &rarr; Configurator

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

### Related issues
#1968

**Comment by chuga** [comment] 2017-09-19 20:42
Marking as a duplicate of #2008

**Closed by chuga** 2017-09-19 20:42 UTC
Labels: device:iPhone X, type:Visual bug, where:Catalog
