### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_MDCFloatingButton"

### ISSUE THREAD

**Issue by Tobistor** [material-components/material-components-ios#3748] opened 2018-05-07 22:51 UTC
I keep getting this error on Xcode Version 9.3 (9E145)
is this something about an absent framework?
I Followed the Objective C coding instruction. My project is objective C based.

 - Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MDCFloatingButton", referenced from:
      objc-class-ref in FrontNavigationController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 ![screen shot 2018-05-07 at 11 28 58 pm](https://user-images.githubusercontent.com/38978317/39728383-993345ea-524e-11e8-9393-2d28616f8b85.png)
 

### Reproduction steps
 - pod install
 - #import "MaterialAppBar.h"
   #import "MaterialButtons.h"
   #import "MaterialCollections.h"
 - followed instruction only (7. Add a floating action button:)

### Version number
 55.0.1

**Comment by Tobistor** [comment] 2018-05-08 08:15
I resolved the issue by adding these 3 frameworks to my project and build was successful
-MaterialComponents.framework
-MDFInternationalization.framework
-MDFTextAccessibility.framework

Just a little help please, Now that the FAB is visible. How do I make it call up/ Open a class which has it's User Interface hardcoded (Mean I didn't use storyboard view and xib or any drag and drop view controller). 
Name of the view to be launched by FAB button when touched is "MainViewController" written in Objective C.
Thanks.

**Comment by romoore** [comment] 2018-05-08 12:55
Hi @Tobistor . Sorry you were having trouble getting the FAB working.  If you haven't already, you might try a `pod update` and see if that works correctly for the FAB.  If you don't mind, it can help to post your Podfile (or the relevant section) here so we can try to reproduce the issue.

From what you describe in your last comment, you may be asking about the [Masked Transition component](https://github.com/material-components/material-components-ios/tree/develop/components/MaskedTransition). It provides a way of transforming a FAB (or similar view) into a presented view.  The MaskedTransitionTypicalUse.swift example is [an example of how to use the Masked Transition component](https://github.com/material-components/material-components-ios/blob/develop/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift).

![mt-example](https://user-images.githubusercontent.com/1753199/39758217-3e59a502-529d-11e8-9628-c3353a4c7d07.gif)

**Comment by Tobistor** [comment] 2018-05-08 16:37
Thanks for your response. Guess I've been mis-understood I had an existing project which I added MDC Fab to, which was cool.  I like 
 to take it further by making MDC Fab open/start another view (MainViewController). What lines of code (Objective C) to apply?
Thanks.

**Comment by jverkoey** [comment] 2018-05-08 17:54
Hi @Tobistor — if I understand correctly you want to present a view controller in response to tapping on a fab button. You can use a fab button like a standard UIButton.

Some resources:

- [How to present a view controller](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-presentviewcontroller)
- [How to respond to UIButton taps](https://developer.apple.com/documentation/uikit/uibutton)

Closing this because it sounds like your MDC-specific questions have been addressed.

**Closed by jverkoey** 2018-05-08 17:54 UTC
Labels: [Buttons]

**Comment by Tobistor** [comment] 2018-05-08 18:18
Thanks for the time. Here is how I sorted it. 
I typed the following inside the method:

- (void)fabDidTap:(id)sender {
    MDCFloatingButton *button = (MDCFloatingButton *)sender;
    button.selected = !button.isSelected;
    
    MainViewController *mysocial = [MainViewController alloc];
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:mysocial];
    nav.modalPresentationStyle = UIModalPresentationFormSheet;
    
    [self presentViewController:nav animated:YES completion:NULL];
