### ISSUE TITLE
[TextField] Underline lineheight not working properly

### ISSUE THREAD

**Issue by ravipxm** [material-components/material-components-ios#2286] opened 2017-10-26 11:20 UTC
When you set the underline.lineheight and when textfield lose the focus, the line height will revert back to the default value rather than the value we did set.

**Steps to reproduce**
1.  set underline.lineheight value
2. run the app/demo
3. you will see the effect of lineheight but now tap on the text field
4. Now either go to the next text field or hide the keyboard, you will see that text will have default lineheight.

**Version**
38.0.0

Thanks for this wonderful lib

**Comment by willlarche** [comment] 2017-11-01 02:16
@ravipxm , are you using a text input controller like MDCTextInputControllerDefault? If so, it overrides any underline choices you make to the text field. This is by design since the controller's job is to style the textfield. 

However, we could add API to customize the controller.

**Comment by ravipxm** [comment] 2017-11-01 03:33
@willlarche, yes I am using input controller MDCTextInputControllerDefault.

Thanks for your reply.

**Comment by taniakulakovskaya** [comment] 2017-12-06 00:45
Still having the same issue. All customization is done in MDCTextInputControllerDefault

```
            controller.activeColor = .parksGreen
            controller.normalColor = .parksLightGreen
            controller.textInput?.underline?.lineHeight = 2.0
            controller.textInput?.font = UIFont(name: "OpenSans-Regular", size: 16.0)
```
The outcome is:
![img_7558](https://user-images.githubusercontent.com/32332428/33638563-76664220-da2f-11e7-834f-6a72e61965e6.jpg)
![img_7559](https://user-images.githubusercontent.com/32332428/33638581-876aa606-da2f-11e7-8694-7b1c652ed09f.jpg)
![img_7560](https://user-images.githubusercontent.com/32332428/33638582-879dfba0-da2f-11e7-9eea-ed29f1b61f3c.jpg)

**Comment by willlarche** [comment] 2017-12-11 17:21
Underline height varies based on the state of the controller. I've added API for it in #2633 which should be merged soon.

**Comment by jverkoey** [comment] 2018-08-24 15:07
Looks like https://github.com/material-components/material-components-ios/pull/2633 resolved this.

**Closed by jverkoey** 2018-08-24 15:07 UTC
Labels: [TextFields], type:Bug
