### ISSUE TITLE
[Tabs] Re-enable test that is throwing an exception

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3220] opened 2018-04-03 23:03 UTC
testTabBarControllerEncoding is throwing an exception

github/develop
Select MDCDragons Target
Product - Test

#0	0x000000010e2dfc54 in UICollectionViewFlowLayoutBreakForInvalidSizes ()
#1	0x000000010e2e38ae in -[_UIFlowLayoutSection logInvalidSizesForHorizontalDirection:warnAboutDelegateValues:] ()
#2	0x000000010e2e19dc in -[_UIFlowLayoutSection computeLayout] ()
#3	0x000000010e26625e in __76-[UICollectionViewFlowLayout _updateItemsLayoutForRect:allowsPartialUpdate:]_block_invoke ()
#4	0x000000010d263b4e in -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] ()
#5	0x000000010e26606b in -[UICollectionViewFlowLayout _updateItemsLayoutForRect:allowsPartialUpdate:] ()
#6	0x000000010e2666f1 in -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] ()
#7	0x000000010e25efd4 in -[UICollectionViewFlowLayout prepareLayout] ()
#8	0x0000000127480cc9 in -[MDCItemBarFlowLayout prepareLayout] at /Users/iangordon/projects/gh-material-components-ios/components/Tabs/src/private/MDCItemBar.m:788
#9	0x000000010e28bf79 in -[UICollectionViewData _prepareToLoadData] ()
#10	0x000000010e28ee48 in -[UICollectionViewData collectionViewContentRect] ()
#11	0x000000010e21570a in -[UICollectionView setFrame:] ()
#12	0x000000012747c554 in -[MDCItemBar layoutSubviews] at /Users/iangordon/projects/gh-material-components-ios/components/Tabs/src/private/MDCItemBar.m:280
#13	0x000000010d823808 in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#14	0x0000000111a1961a in -[CALayer layoutSublayers] ()
#15	0x0000000111a1d82b in CA::Layer::layout_if_needed(CA::Transaction*) ()
#16	0x000000010d80d68d in -[UIView(Hierarchy) layoutBelowIfNeeded] ()
#17	0x00000001274ec264 in -[MDCTabBarViewController transitionViewsWithoutAnimationFromViewController:toViewController:] at /Users/iangordon/projects/gh-material-components-ios/components/Tabs/src/MDCTabBarViewController.m:219
#18	0x00000001274ec09e in -[MDCTabBarViewController setSelectedViewController:] at /Users/iangordon/projects/gh-material-components-ios/components/Tabs/src/MDCTabBarViewController.m:200
#19	0x0000000127895569 in -[MDCTabBarControllerEncodingTests testTabBarControllerEncoding] at /Users/iangordon/projects/gh-material-components-ios/components/Tabs/tests/unit/MDCTabBarControllerEncodingTests.m:69

Internal issue: b/37901472

**Comment by romoore** [comment] 2018-08-21 18:13
Duplicate of #1981

**Closed by romoore** 2018-08-21 18:13 UTC
Labels: Internal, Needs actionability review, [Tabs], type:Bug
