### ISSUE TITLE
Make all dynamic fonts logic consistent.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#4346] opened 2018-06-01 15:34 UTC
We have different ways of achieving the same dynamic font in different places.
We should have one approach to all.

**Comment by ianegordon** [comment] 2018-06-01 16:44
Can you be more specific and give some example of the inconsistency?
Is there a particular approach you prefer or would rather avoid?

**Comment by samskiter** [comment] 2018-06-04 11:09
I have a related question to this - is the only way to get automatic dynamic type behaviour on components to use `mdc_setAdjustsFontForContentSizeCategory`? Is there any way to enable the standard iOS `setAdjustsFontForContentSizeCategory` and use standard system fonts? I can't see that UILabels are exposed publicly to allow calling this method, and no external method allows me to enable it.

**Comment by ianegordon** [comment] 2018-06-07 16:01
Hi @samskiter .  As we support iOS 8, we are limited in how quickly we can adopt new APIs. 
 UIContentSizeCategoryAdjusting wasn't added until iOS 10.  We are looking into how to mimic the scaledFont API introduced in iOS 11, which would simplify using the system (or custom) fonts with a specific resizing curve.
Currently, if you enable mdc_setAdjustsFontForSizeCategory, without setting a custom font, it will use the system font, but it will be sized based on our font style resizing curves.

**Comment by samskiter** [comment] 2018-06-07 19:01
Yea I saw that, I think we'd like to use the system sizing curves so we
aren't forced to have to use the MDC typography scheme everywhere.

Could you use an #available block or something to only allow calling the
method on certain iOS versions?

**Comment by samskiter** [comment] 2018-06-11 17:13
@ianegordon would this be something you'd be open to having contributed?

**Comment by ianegordon** [comment] 2018-08-24 14:31
Closing as a duplicate of #4597

**Closed by ianegordon** 2018-08-24 14:31 UTC
Labels: [Typography]
