### ISSUE TITLE
{kokoro} Tests timing out on Xcode 10.1

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6259] opened 2019-01-09 16:26 UTC
When running bazel tests (via .kokoro) on Xcode 10.1, unit tests time-out. The same tests do not timeout when running Xcode 10.0.

```
rsmoore:material-components-ios rsmoore$ ./.kokoro -d bazel -t components/ShadowElevations/... -c test
Running bazel builds...
🛠️  test with Xcode 10.1...
Rewriting imports for bazel...
INFO: Invocation ID: 85d01aea-7b11-46c6-90de-b9b7e5b04637
INFO: Analysed 14 targets (1 packages loaded, 33 targets configured).
INFO: Found 10 targets and 4 test targets...

TIMEOUT: //components/ShadowElevations:unit_tests_IPHONE_X_IN_11_0 (Summary)
      /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_X_IN_11_0/test.log
INFO: From Testing //components/ShadowElevations:unit_tests_IPHONE_X_IN_11_0:
==================== Test output for //components/ShadowElevations:unit_tests_IPHONE_X_IN_11_0:
2019-01-09 16:24:04,610 Will consider the test as test type logic_test to run.
Terminated: 15
================================================================================

TIMEOUT: //components/ShadowElevations:unit_tests_IPHONE_5_IN_8_1 (Summary)
      /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_5_IN_8_1/test.log

TIMEOUT: //components/ShadowElevations:unit_tests_IPHONE_7_PLUS_IN_10_3 (Summary)
      /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_7_PLUS_IN_10_3/test.log
INFO: From Testing //components/ShadowElevations:unit_tests_IPHONE_5_IN_8_1:
==================== Test output for //components/ShadowElevations:unit_tests_IPHONE_5_IN_8_1:
2019-01-09 16:24:04,626 Will consider the test as test type logic_test to run.
Terminated: 15
================================================================================
INFO: From Testing //components/ShadowElevations:unit_tests_IPHONE_7_PLUS_IN_10_3:
==================== Test output for //components/ShadowElevations:unit_tests_IPHONE_7_PLUS_IN_10_3:
2019-01-09 16:24:04,613 Will consider the test as test type logic_test to run.
Terminated: 15
================================================================================

TIMEOUT: //components/ShadowElevations:unit_tests_IPAD_PRO_12_9_IN_9_3 (Summary)
      /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPAD_PRO_12_9_IN_9_3/test.log
INFO: From Testing //components/ShadowElevations:unit_tests_IPAD_PRO_12_9_IN_9_3:
==================== Test output for //components/ShadowElevations:unit_tests_IPAD_PRO_12_9_IN_9_3:
2019-01-09 16:24:04,624 Will consider the test as test type logic_test to run.
Terminated: 15
================================================================================
INFO: Elapsed time: 61.438s, Critical Path: 61.08s
INFO: 4 processes: 4 darwin-sandbox.
INFO: Build completed, 4 tests FAILED, 5 total actions
//components/ShadowElevations:unit_tests_IPAD_PRO_12_9_IN_9_3           TIMEOUT in 61.0s
  /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPAD_PRO_12_9_IN_9_3/test.log
//components/ShadowElevations:unit_tests_IPHONE_5_IN_8_1                TIMEOUT in 61.0s
  /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_5_IN_8_1/test.log
//components/ShadowElevations:unit_tests_IPHONE_7_PLUS_IN_10_3          TIMEOUT in 61.0s
  /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_7_PLUS_IN_10_3/test.log
//components/ShadowElevations:unit_tests_IPHONE_X_IN_11_0               TIMEOUT in 61.0s
  /private/var/tmp/_bazel_rsmoore/9239405992f16fcf43677963a12bd325/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/components/ShadowElevations/unit_tests_IPHONE_X_IN_11_0/test.log

INFO: Build completed, 4 tests FAILED, 5 total actions
Undoing import rewrites for bazel...
rsmoore:material-components-ios rsmoore$ 

```

---
#### Internal data
- Associated internal bug: [b/122740078](http://b/122740078)

**Comment by romoore** [comment] 2019-01-31 13:19
Looks like this is happening sometimes in the Xcode 10.1 kokoro job as well.

https://fusion.corp.google.com/runanalysis/info/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_affected_xcode_1010/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_affected_xcode_1010/KOKORO/af9251ca-7ff4-4757-abef-02b3a3fda9c4/1548907593613/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_affected_xcode_1010%20Build%20%23143/Targets

**Comment by jverkoey** [comment] 2019-02-25 20:12
We appear to be running green 10.1 presubmits now, so I am going to mark this issue as obsolete, but please re-open if I've misunderstood this issue and the problem is still present.

**Comment by jverkoey** [comment] 2019-02-25 20:15
Spoke with @romoore and we are still running into this issue somewhat inconsistently.

**Comment by material-mirror** [comment] 2019-02-25 20:16
The internal issue [b/122740078](http://b/122740078) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment] 2019-04-18 01:24
We may be seeing this in our Xcode 10.1 presubmit jobs on Kokoro as well.

```
2019-04-17 18:09:24.172 xcodebuild[50620:116242]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
Xcode/DerivedData/MDCCatalog-gwfdvkhehobhdcepuvahjrjklwpx/Logs/Test/Test-MDCCatalog-2019.04.17_18-05-29--0700.xcresult/1_Test/Diagnostics/MaterialComponents-Unit-ActivityIndicator-UnitTests-48FDA142-2AE6-4D05-A1B8-1F509DFA703A/MaterialComponents-Unit-ActivityIndicator-UnitTests-8073E926-6259-4742-9C14-D9D88D8EB870/Session-MaterialComponents-Unit-ActivityIndicator-UnitTests-2019-04-17_180924-yAGvU3.log
2019-04-17 18:09:24.173 xcodebuild[50620:90322] [MT] IDETestOperationsObserverDebug: (D8DCBE0F-DC68-4686-AB63-69779D19BE2E) Beginning test session MaterialComponents-Unit-ActivityIndicator-UnitTests-D8DCBE0F-DC68-4686-AB63-69779D19BE2E at 2019-04-17 18:09:24.173 with Xcode 10B61 on target <DVTiPhoneSimulator: 0x7fcaa73a24d0> {
		SimDevice: iPhone 7 (7D644508-F6E2-4FED-A37D-73602C788D82, iOS 12.1, Shutdown)
} (12.1 (16B91))
** INTERNAL ERROR: Uncaught exception while building **
Uncaught Exception: *** -[_NSStdIOFileHandle writeData:]: Broken pipe
```

**Comment by vidhyasri2106** [comment] 2019-06-18 11:56
Any update on this?

**Closed** 2021-08-13 17:44 UTC
Labels: type:Bug, skill:Kokoro, skill:Bazel
