### ISSUE TITLE
[Ripple] Internal issue: b/139733967

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8348] opened 2019-08-20 14:45 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/139733967](http://b/139733967) for more details.

---
#### Internal data
- Associated internal bug: [b/139733967](http://b/139733967)

**Comment by yarneo** [comment] 2019-08-22 13:22
The issue is concluded and resolved by this PR: https://github.com/material-components/material-components-ios/pull/8354

**Closed by yarneo** 2019-08-22 13:22 UTC
Labels: [Ripple], type:Bug
