### ISSUE TITLE
[Tabs] MDCTabBarView sometimes miscalculates the sizes of custom views

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#8546] opened 2019-10-07 12:19 UTC
When using multiple custom views, sometimes all tabs are positioned overlapping one another.

## Steps reproduce
1. Have 3 items with `.clusteredCentered` layout. 2 items are a customView

----
Related to me by @mrhappyasthma : 

Its using the centered style with 2 of my custom items. They seem to overlap.

I'm wondering if somehow my contentFrame/intrinsicContentSize calculation is returning bad values, but whenever debugging I can't find where that's occurring.
If you have any ideas, please let me know!

---
#### Internal data
- Associated internal bug: [b/142338742](http://b/142338742)

**Comment by mrhappyasthma** [comment] 2019-10-08 00:05
I found a way to repro what I believe to be the issue. It's a bit convoluted, but the problem seems to be if `intrinsicContentSize` returns CGSizeZero (such as when it's not yet in the view hierarchy), but you call `setSelectedItem:` on the tabbed bar view for that item.

The -intrinsicContentSize is called and returns zero in this case.

However after the view is added to the view hierarchy and is sized correctly, the size of the cell for the item is never corrected.

```
@@ -88,6 +88,9 @@ static NSString *const kPreferredLayoutMenuAccessibilityLabel = @"Change preferr
 }
 
 - (CGSize)intrinsicContentSize {
+  if (!self.aSwitch.superview) {
+    return CGSizeZero;
+  }
   if (self.aSwitch.isOn) {
     return CGSizeMake(self.aSwitch.intrinsicContentSize.width * 2,
                       self.aSwitch.intrinsicContentSize.height * 2);
@@ -155,7 +158,6 @@ static NSString *const kPreferredLayoutMenuAccessibilityLabel = @"Change preferr
   self.tabBar = [[MDCTabBarView alloc] init];
   self.tabBar.tabBarDelegate = self;
   self.tabBar.delegate = self;
-  [self.view addSubview:self.tabBar];
 
   NSMutableArray<UIImage *> *itemIcons = [NSMutableArray array];
   [itemIcons addObject:[[UIImage imageNamed:@"Home"]
@@ -196,7 +198,9 @@ static NSString *const kPreferredLayoutMenuAccessibilityLabel = @"Change preferr
   switchView.animationTimingFunction = self.tabBar.selectionChangeAnimationTimingFunction;
 
   self.tabBar.items = @[ item1, item2, item6, item4, item5, item3 ];
-  self.tabBar.selectedItem = item4;
+  self.tabBar.selectedItem = item6;
+
+  [self.view addSubview:self.tabBar];
 
   self.tabBar.translatesAutoresizingMaskIntoConstraints = NO;
   if (@available(iOS 11.0, *)) {
```

**Comment by mrhappyasthma** [comment] 2019-10-08 00:21
I don't actually propose this as a fix, but it seems when the bounds change as a result of the tab bar view being added to the view hierarchy, the subviews are never reloaded.

Keeping the above changes, adding this hack would fix it:

```
- (void)setBounds:(CGRect)bounds {
  [super setBounds:bounds];
  [self setNeedsLayout];
  [self layoutIfNeeded];
}
```

This would trigger a new layout subviews which recalculates intrinsic content size.

**Comment by mrhappyasthma** [comment] 2019-10-08 00:39
Actually the more I dig into it, the more my original override of setBounds: was triggering as part of layout constraints (which I'm not too familiar with). Gonna try reproducing under a manual layout and see if I can debug further.

**Comment by mrhappyasthma** [comment] 2019-10-08 01:09
I'm able to induce a similar scenario by using manual layout.

```
  // Set to some reasonable dummy frame (at least for iPhone 6).
  self.tabBar.frame = CGRectMake(0, 100, self.view.bounds.size.width, 72);

  [self.view addSubview:self.tabBar];

//  self.tabBar.translatesAutoresizingMaskIntoConstraints = NO;
//  if (@available(iOS 11.0, *)) {
//    [self.view.layoutMarginsGuide.topAnchor constraintEqualToAnchor:self.tabBar.topAnchor].active =
//        YES;
//  } else {
//    [self.topLayoutGuide.bottomAnchor constraintEqualToAnchor:self.tabBar.topAnchor].active = YES;
//  }
//  [self.view.leftAnchor constraintEqualToAnchor:self.tabBar.leftAnchor].active = YES;
//  [self.view.rightAnchor constraintEqualToAnchor:self.tabBar.rightAnchor].active = YES;
```

**Comment by romoore** [comment] 2019-10-08 12:38
Thanks, @mrhappyasthma . I am curious why your view has an `intrinsicContentSize` of `CGSizeZero`? Does your content never have an intrinsic size (it fully adjusts to its frame)?

**Comment by romoore** [comment] 2019-10-09 01:18
Spoke offline with @mrhappyasthma and we agreed that the root cause was a change in the calculation of `intrinsicContentSize` from the custom view. The next steps on this will be:

1. @mrhappyasthma will adjust the `intrinsicContentSize` implementation in his custom view to always return the rendered size. If the size changes, then the custom view will call `[self.superview setNeedsLayout]` to trigger a layout pass with the new size.
2. @romoore will update the documentation for `MDCTabBarViewCustomViewable` to try and prevent a similar solution for future clients.

**Comment by mrhappyasthma** [comment] 2019-10-16 04:11
I verified updating the intrinsicContentSize to compute the correct value and it resolved the problem mentioned above.

**Comment by material-mirror** [comment] 2019-11-14 21:16
The internal issue [b/143705920](http://b/143705920) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-11-14 21:16 UTC
Labels: [Tabs], type:Bug
