### ISSUE TITLE
MDCButton setBackgroundColor (without forState) doesn't interact well with appearance

### ISSUE THREAD

**Issue by Tilps** [material-components/material-components-ios#3118] opened 2018-03-20 02:58 UTC
### Overview
MDCButton setBackgroundColor: is documented as a convenience for setBackgroundColor:forState: passing state as normal, however its implementation does not call setBackgroundColor:forState: at all.
This is a problem because unless the forState: function is called the appearance proxy doesn't know that this instance has overridden the default and so the default can get reapplied at future times.

### Reproduction steps
 - I don't have exact repro steps at hand, but something approximately like this might work...
 - Add an MDCFlatButton.
  - Call setBackgroundColor(UIColor.red) on it after the view is in the hierarchy.
  - Add a tap handler which removes the view from the hierarchy, and puts it back.
  - At this point the background should be red on first view - but tap will cause it to return to transparent.
 - Replace the call to setBackgroundColor(UIColor.red, for: .normal) and the everything now works fine...

### Version number
 - 48

### Operating system and device
Originally checked on an iPhone SE running iOS 10.3.2.

**Comment by romoore** [comment] 2018-03-20 12:46
@Tilps Can you clarify if the reproduction steps are to call `setBackgroundColor:UIColor.red` on the UIAppearance proxy or on the instance?

**Comment by Tilps** [comment] 2018-03-20 21:04
My problematic scenario code only directly interacts with the instance and not the proxy. (MDCFlatButton itself interacts with the proxy in its initialize, setting up the default value which can get applied to the instance unexpectedly.)

**Comment by romoore** [comment] 2018-03-21 12:35
Thanks for the clarification. If I understand the problem correctly, the root cause is #2782 . Since none of your code directly called `setBackgroundColor:forState:`, the UIAppearance proxy wasn't disabled and the values coded in `+initialize` are being passed once the button enters the view hierarchy.  However, if you call `-setBackgroundColor:forState:` directly, UIAppearance won't have an effect and the bug goes away.

I'm going to close this as a duplicate of #2782, but please reopen it if I've misunderstood the problem.

**Closed by romoore** 2018-03-21 12:35 UTC
Labels: type:Visual bug, where:Buttons

**Comment by Tilps** [comment] 2018-03-21 21:05
I think you have understood the problem - and fixing 2782 would certainly stop the specific problem case reported here.
I do however wonder whether it would still be worth a documentation change or implementation change, so that the variant scenario where user code explicitly sets the appearance proxy and then calls setBackgroundColor: thinking its an alias for setBackgroundColor:forState: isn't confused when it doesn't work.
