### ISSUE TITLE
Internal issue: b/131745902

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7313] opened 2019-05-01 16:15 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/131745902](http://b/131745902) for more details.

---
#### Internal data
- Associated internal bug: [b/131745902](http://b/131745902)

**Comment by jverkoey** [comment] 2019-05-01 21:15
Duplicate of https://github.com/material-components/material-components-ios/issues/7312

**Closed by jverkoey** 2019-05-01 21:15 UTC
Labels: Needs actionability review, type:Feature request
