### ISSUE TITLE
MDCAppBar shift behavior flexibility

### ISSUE THREAD

**Issue by babakbo** [material-components/material-components-ios#4602] opened 2018-07-20 17:01 UTC
## Feature Request/Suggestion
MDCAppBar supports 3 different shift behaviors (.disable, .enabled, .enabledWithStatusBar). 
However, minimumHeight is only considered in the .disable mode. Using the other shift behaviors, the whole stackView would be shifted off the screen regardless of minimumHeight.

In addition, headerContentImportance is only effective when the shift behavior is enabled (or enabledWithStatusBar). As a result, we don't have a way to set the stackview.bottomBar which stays on screen all the time, while shifting only the navigation bar when user scrolls up and bringing it back as soon as user scrolls down.

Furthermore, if we want to keep the statusbar on the screen at all time, the navbar and statusbar overlap while the navbar is shifting off the screen. Looks like there should be a statusbar background view to prevent that from happening.

**Comment by samskiter** [comment] 2018-07-20 17:12
Apologies, this is a duplicate of https://github.com/material-components/material-components-ios/issues/4393

**Closed by samskiter** 2018-07-20 17:12 UTC
Labels: Needs actionability review
