### ISSUE TITLE
[Ink] Demo content view is offset after rotation to Landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3711] opened 2018-05-04 13:40 UTC
### Overview
The Ink demo content is incorrectly offset from the App Bar after rotation from Portrait to Landscape. This results in a black "box" below the App Bar.

![simulator screen shot - iphone x - 2018-05-04 at 09 39 07](https://user-images.githubusercontent.com/1753199/39631036-2054745e-4f7f-11e8-9bcc-39f5a0801233.png)

### Reproduction steps
1. Launch the Catalog in Portrait
1. Open Ink &rarr; Start Demo
1. Rotate to Landscape

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3710

**Comment by rami-a** [comment] 2018-10-09 19:43
I tried to reproduce this issue and it looks like it was fixed inadvertently. Closing this out.

**Closed by rami-a** 2018-10-09 19:43 UTC
Labels: Internal, [Chips], app:Catalog, good first issue, type:Bug
