### ISSUE TITLE
[Typography] Consider deprecating MDCTypography

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2626] opened 2017-12-06 21:00 UTC
Currently (for another few days at least 😉 ) we officially recommend using the system font over custom fonts.

We would want to capture the current set of fonts and the opacities.

**Comment by jverkoey** [comment] 2018-10-09 09:37
Duplicate of https://github.com/material-components/material-components-ios/issues/4013

**Closed by jverkoey** 2018-10-09 09:37 UTC
Labels: Internal, [Typography], skill:Client migrations, skill:Deprecations, type:API change
