### ISSUE TITLE
[Buttons] MDCButton titleFontForState: does not default to .normal state

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3806] opened 2018-05-10 02:19 UTC
### Overview
MDCButton's `titleFontForState:` will return a system font if a state is not explicitly set. This may be intentional, but does not match the behavior of `titleForState:`, `titleColorForState:`, `titleShadowColorForState:` nor `attributedTitleForState:`.  I think it will be more expected for clients if the titleFont defaults to the value for the `.normal` state to match the related properties.

### Reproduction steps

```objectivec
- (void)testButtonFontThemer {
  // Given
  MDCButton *button = [[MDCButton alloc] init];
  MDCBasicFontScheme *fontScheme = [[MDCBasicFontScheme alloc] init];

  // When
  [button setTitleFont:fontScheme.button forState:UIControlStateNormal];

  // Then
  UIControlState maximalControlState = UIControlStateNormal | UIControlStateSelected |
      UIControlStateDisabled | UIControlStateHighlighted;
  for (NSUInteger state = 0; state <= maximalControlState; ++state) {
      XCTAssertEqualObjects([button titleFontForState:state], fontScheme.button);
   }
}
```

### Version number
49.0.0

---
#### Internal data
- Associated internal bug: [b/117179029](http://b/117179029)

**Comment by romoore** [comment] 2018-11-02 14:45
Duplicate of #3222

**Closed by romoore** 2018-11-02 14:45 UTC
Labels: [Buttons], skill:Refactoring, type:Bug
