### ISSUE TITLE
Add example targets in build files

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#5256] opened 2018-09-26 19:27 UTC
To make the release cop's job easier we should make build targets for all the examples.

---
#### Internal data
- Associated internal bug: [b/117144313](http://b/117144313)

**Comment by romoore** [comment] 2018-10-03 14:13
Would we also be able to have the compile in CI?

**Comment by jverkoey** [comment] 2018-12-21 18:46
Duplicate of https://github.com/material-components/material-components-ios/issues/2641

**Closed by jverkoey** 2018-12-21 18:46 UTC
Labels: skill:Bazel, skill:Kokoro, type:Internal cleanup
