### ISSUE TITLE
[List] Wrong size for list cells - only on iOS12 / Xcode 10

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#4649] opened 2018-07-26 19:53 UTC
List cells size are calculated or laid out incorrectly in "List Cell Example":

![image](https://user-images.githubusercontent.com/2329102/43324512-4a237f2e-9182-11e8-8145-0f1c11721290.png)

---
#### Internal data
- Associated internal bug: [b/117177912](http://b/117177912)

**Comment by andrewoverton** [comment] 2018-08-15 14:34
I looked into this last Friday--my best guess is it's an Apple self-sizing cell regression. I think we should keep an eye on it, it might be worth waiting for iOS 12 to come out to reevaluate.

**Comment by andrewoverton** [comment] 2018-08-21 16:12
Relevant forum: https://forums.developer.apple.com/thread/107612

**Comment by doganov** [comment] 2018-12-21 07:58
Given that in two months Xcode 10 will be required for submitting iOS apps to the App Store, not supporting Xcode 10 is pretty serious.

**Comment by romoore** [comment] 2018-12-21 13:50
Still present with the Xcode 10.0 (10A255) iOS 12 simulator.

![simulator screen shot - iphone 7 - 2018-12-21 at 08 48 31](https://user-images.githubusercontent.com/1753199/50345487-4ad1a100-04fd-11e9-9967-0cd707f4d454.png)

**Comment by romoore** [comment] 2018-12-21 13:51
Assigning to @randallli  to prioritize against our backlog.

**Comment by romoore** [comment] 2019-07-31 17:56
Closing this due to inactivity greater than 6 months. Please feel free to reopen if you believe it should be worked on in the near future.

**Closed by romoore** 2019-07-31 17:56 UTC
Labels: [List], iOS:12, type:Bug
