### ISSUE TITLE
Add test for adding and removing an ink view from the view hierarchy during animation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#449] opened 2016-04-25 15:13 UTC
There was some visual appearance issues with the ink when the view was added back into a view hierarchy.

**Comment by romoore** [comment] 2017-06-26 19:14
Closing this issue since there is not a clear success case for this test.  Please open a new issue if the motivating defect can be reproduced.

**Closed by romoore** 2017-06-26 19:14 UTC
Labels: Triaged, type:Feature request, where:Ink
