### ISSUE TITLE
[TextFields] MDCTextInputController underline labels with multiline property

### ISSUE THREAD

**Issue by freakdragon** [material-components/material-components-ios#7133] opened 2019-04-12 13:00 UTC
## Feature Request/Suggestion

It will be nice to add multiline underline labels (for errors). That's Why I tried to override some methods for it. Looks like multiline errors work as needed. You can implement it as feature.

```
import MaterialComponents.MaterialTextFields


extension MDCTextField {
    func setDefaultTheme() -> MDCTextField {
        leadingUnderlineLabel.numberOfLines = 0
        leadingUnderlineLabel.lineBreakMode = .byWordWrapping
        trailingUnderlineLabel.numberOfLines = 0
        trailingUnderlineLabel.lineBreakMode = .byWordWrapping
        textInsetsMode = .ifContent
        
        return self
    }
}

class CustomMDCTextInputControllerOutlined: MDCTextInputControllerOutlined {
    
    override func textInputDidLayoutSubviews() {
        super.textInputDidLayoutSubviews()
        forceUpdateConstraints()
    }
    
    private let MDCTextInputControllerBaseDefaultPadding: CGFloat = 12
    private let MDCTextInputControllerBaseDefaultUnderlinePadding: CGFloat = 5
    
    override func textInsets(_ defaultInsets: UIEdgeInsets) -> UIEdgeInsets {
        var textInsets = super.textInsets(defaultInsets)
        if (!self.isFloatingEnabled || self.textInput == nil) {
            return textInsets;
        }
        
        let scale = UIScreen.main.scale       
        
        let leadingOffset =
            self.textInput!.leadingUnderlineLabel.bounds.height
        let trailingOffset =
            self.textInput!.trailingUnderlineLabel.bounds.height
        var underlineOffset: CGFloat = 0
        switch (self.textInput!.textInsetsMode) {
        case .always:
            underlineOffset +=
                max(MDCCeil(self.textInput!.leadingUnderlineLabel.font.lineHeight * scale) / scale, MDCCeil(self.textInput!.trailingUnderlineLabel.font.lineHeight * scale) / scale)
            break;
        case .ifContent:
            var contentConditionalOffset: CGFloat = 0;
            if ((self.textInput!.leadingUnderlineLabel.text ?? "").count > 0) {
                contentConditionalOffset = leadingOffset;
            }
            if ((self.textInput!.trailingUnderlineLabel.text ?? "").count > 0) {
                contentConditionalOffset = max(contentConditionalOffset, trailingOffset);
            }
            underlineOffset += contentConditionalOffset
            break;
        case .never:
            break;
        }
        textInsets.bottom = underlineOffset + MDCTextInputControllerBaseDefaultPadding + MDCTextInputControllerBaseDefaultUnderlinePadding;
        return textInsets
    }
    
    private func forceUpdateConstraints() {
        if let textInput = self.textInput {
            textInput.leadingUnderlineLabel.layoutIfNeeded()
            textInput.leadingUnderlineLabel.setNeedsUpdateConstraints()
            textInput.leadingUnderlineLabel.updateConstraintsIfNeeded()
            textInput.trailingUnderlineLabel.layoutIfNeeded()
            textInput.trailingUnderlineLabel.setNeedsUpdateConstraints()
            textInput.trailingUnderlineLabel.updateConstraintsIfNeeded()
            textInput.layoutIfNeeded()
            textInput.setNeedsUpdateConstraints()
            textInput.updateConstraintsIfNeeded()
        }
    }
}

```

---
#### Internal data
- Associated internal bug: [b/130431453](http://b/130431453)

**Comment by andrewoverton** [comment] 2019-04-12 14:16
Hi @freakdragon, we've been looking at this functionality for a while but hadn't yet arrived at a good way of doing it. Would you mind adding a screenshot or gif of your multiline underline labels? 😄

**Comment by freakdragon** [comment] 2019-04-15 06:08
Hi @andrewoverton, it looks like this.
![Uploading textfields_multiline_errors.gif…]()

**Comment by adrianodiasx93** [comment] 2019-05-13 16:56
+1

**Comment by romoore** [comment] 2019-05-13 17:07
It looks like this is for Outlined text fields, which would make this a duplicate of https://github.com/material-components/material-components-ios/issues/5762. Closing as a duplicate, but please reopen if my reading is incorrect.

**Closed by romoore** 2019-05-13 17:07 UTC
Labels: [TextFields], type:Feature request

**Comment by tranjustin0411** [comment] 2019-06-19 15:53
I had to make one few changes to make this works for me:
1. In the forceUpdateConstraints() method I added a constraints             textInput.leadingUnderlineLabel.topAnchor.constraint(equalTo: textInput.trailingUnderlineLabel.bottomAnchor, constant: -5).isActive = true

2. In the input field func textField shouldChangeCharactersIn I have to call the method
                let test = Input.setDefaultTheme()
                test.leadingUnderlineLabel.lineBreakMode = .byWordWrapping
                test.leadingUnderlineLabel.numberOfLines = 4
                inputController?.textInputDidLayoutSubviews()

**Comment by hardikamal** [comment] 2020-09-02 08:53
@freakdragon Could you please provide steps on how do I use this?

**Comment by freakdragon** [comment] 2020-09-02 09:08
@hardikamal you just need to declare CustomMDCTextInputControllerOutlined like this (globally in your view controller):

`var textFieldController = CustomMDCTextInputControllerOutlined()`

And also you must set theme to your MDCTextInput like this (for example in `viewDidLoad` method of your view controller):

 `textField.setDefaultTheme()`

And don't forget to set your mdc text field to mdc controller like this (for example in `viewDidLoad` method of your view controller):

`textFieldController.textInput = textField`

**Comment by hardikamal** [comment] 2020-09-02 09:32
@freakdragon How does the auto layout work when the error is shown or hidden?
I tried the above steps but that does not work.

**Comment by freakdragon** [comment] 2020-09-02 09:44
That was a long time ago. May be, now it works from box without need of overriding MDCTextInputController. And, may be, this code breaks it. This code was used for MaterialComponents/TextFields version "84.6.0". Look here https://github.com/material-components/material-components-ios/issues/5762
Also you must be sure that your layout is correct for autolayout using.

**Comment by andrewoverton** [comment] 2020-09-02 18:38
Hi everyone, I would encourage you to use the new text fields. You can read about them here:
https://github.com/material-components/material-components-ios/tree/develop/components/TextControls
