### ISSUE TITLE
[AppBar] Add a theming extension

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6864] opened 2019-03-13 15:45 UTC
This was filed as an internal issue. If you are a Googler, please visit [b/128513851](http://b/128513851) for more details.

---
#### Internal data
- Associated internal bug: [b/128513851](http://b/128513851)

**Comment by romoore** [comment] 2019-03-13 19:14
Duplicate of https://github.com/material-components/material-components-ios/issues/6866

**Closed by romoore** 2019-03-13 19:14 UTC
Labels: Client-blocking, [AppBar], type:Feature request
