### ISSUE TITLE
[MDCButtonBar] Button ink is not centered on the button item in a MDCButtonBar

### ISSUE THREAD

**Issue by chickenblood** [material-components/material-components-ios#5374] opened 2018-10-09 17:51 UTC
## Feature Request/Suggestion

See screenshot. If you have more than one UIBarButtonItem in a MDCButtonBar, the ink is no longer centered over the button that you tap.

## Additional context

![nnn](https://user-images.githubusercontent.com/18295993/46688028-3134e480-cbb1-11e8-8390-1adacf7b4a8b.png)

![bff](https://user-images.githubusercontent.com/18295993/46688032-385bf280-cbb1-11e8-81da-6c58217a9fa9.png)

**Comment by chickenblood** [comment] 2018-10-09 19:58
Commenting out these lines fixes the issue: https://github.com/material-components/material-components-ios-codelabs/blob/cfbbfde294272afeac1972140ab5ff53e1789556/MDC-111/Swift/Starter/Pods/MaterialComponents/components/ButtonBar/src/MDCButtonBar.m#L245-L250

**Comment by chickenblood** [comment] 2018-10-09 20:19
On further inspection, it looks like the "else" clasuse here is the issue:

https://github.com/material-components/material-components-ios/blob/e785745/components/Buttons/src/MDCButton.m#L256

IMHO, we would never want to execute the else path, i.e. the if (_inkView.inkStyle == MDCInkStyleUnbounded && _inkView.usesLegacyInkRipple) is unnecessary.
Maybe I'm wrong?

**Comment by jverkoey** [comment] 2018-10-09 22:55
Duplicate of https://github.com/material-components/material-components-ios/issues/4253

**Closed by jverkoey** 2018-10-09 22:55 UTC
Labels: [ButtonBar], type:Bug
