### ISSUE TITLE
[Buttons] MDCButton default size is incorrect

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#1929] opened 2017-08-30 10:31 UTC
According to the [material spec](https://material.io/guidelines/components/buttons.html#buttons-flat-buttons) default raised and flat buttons should have `36dp` in height. However `MDCButton` implementations default to `33dp`. It also does not have correct _minimum width_ and _touch target height_.

Height example:
```
MDCButton *flatButton = [[MDCFlatButton alloc] initWithFrame:CGRectZero];
[flatButton setTitle:@"Title" forState:UIControlStateNormal];
[flatButton sizeToFit];
CGSize flatButtonSize = flatButton.bounds.size;
NSLog(@"Flat button: (%f, %f)", flatButtonSize.width, flatButtonSize.height);

MDCButton *raisedButton = [[MDCRaisedButton alloc] initWithFrame:CGRectZero];
[raisedButton setTitle:@"Title" forState:UIControlStateNormal];
[raisedButton sizeToFit];
CGSize raisedButtonSize = flatButton.bounds.size;
NSLog(@"Raised button: (%f, %f)", raisedButtonSize.width, raisedButtonSize.height);
```

Outputs:  
```
Flat button: (70.000000, 33.000000)
Raised button: (70.000000, 33.000000)
```

---
#### Internal data
- Associated internal bug: [b/117179252](http://b/117179252)

**Comment by romoore** [comment] 2017-08-30 12:24
Relevant section of the spec: https://material.io/guidelines/components/buttons.html#buttons-style

**Comment by ajsecord** [comment] 2017-08-30 12:51
Thanks for the report—that's definitely odd. We'll look into it.

**Comment by romoore** [comment] 2017-08-30 15:35
I want to discuss the best approach for this with @randallli  when he returns next week.

**Comment by randallli** [comment] 2017-09-11 14:12
What were the options and concerns? are we worried that it would change for clients suddenly?

**Comment by romoore** [comment] 2017-09-11 14:18
It is a general discussion around the class hierarchies for our buttons.  Although it might be possible to set minimum heights for some MDCButton and some subclasses (like MDCRaisedButton or MDCFlatButton), other subclasses should not have the same minimum heights (like MDCButtonBarButton).  In general, it seems like setting the minimum height for the button class hierarchy is a bit messy.

So before I started digging into all of the possible subclasses and tweaking each to match the spec, I was hoping to take a broader look at whether MDCButton should be so heavily subclassed or whether we should consider another approach.

**Comment by randallli** [comment] 2017-09-11 14:24
Long term I would like to remove subclasses of MDCButton. We would create factory methods for creating the styled buttons and only keep the subclasses for Interface Builder reasons.
Sort term we would just change the starting size and let clients decide if they really need to change it they can.

**Comment by romoore** [comment] 2017-09-11 14:38
In that case, if I have an MDCFlatButton using an 11-point font that resolves to 50x28 pt when calling `-sizeToFit`, do you think we should expand that out to the Material-specified 88x36 (or 64x36 inside dialogs) pt minimum? Should we track when setBounds or setFrame is called on the button and stop "correcting" the minimum size in that case?

On a related note, we need to override the `hitAreaInsets` value so that the warning NSLog message in `-pointInside:withEvent:` doesn't trigger for defaulted components.

**Comment by randallli** [comment] 2017-09-11 14:59
We can do all these magical things and more, but lets put it in a mutator instead of inside MDCButton. 

As for the default button: we should make sure that when a client creates a MDCButton it conforms to our specs. If you start editing the properties (like font to 11) we would expect clients to recalculate the size or call our mutator.

**Comment by romoore** [comment] 2017-09-11 15:20
If we are going for default button sizes but not necessarily during layout, should we verify/override the CGRect passed to `initWithFrame:` to ensure it meets the minimum size requirements?  Perhaps my example with a font size was misleading.  Our buttons fail to meet minimums even by just setting the title to something short like "NO".

Regarding mutators, do you anticipate something like this?

```objectivec

@interface CustomAlertController : UIViewController {
}

@implementation CustomAlertController {

- (void)viewDidLoad {
  [super viewDidLoad];
  self.noButton = [[MDCFlatButton alloc] init];
  [self.noButton setTitle:@"No" forState:UIControlStateNormal];
  [self.addSubview:self.noButton]

  self.yesButton = [[MDCFlatButton alloc] init];
  [self.yesButton setTitle:@"Yes" forState:UIControlStateNormal];
  [self.addSubview:self.yesButton];
}

- (void)viewWillLayoutSubviews {
  [super viewWillLayoutSubviews];
  // Update the bounds and hitAreaInsets to ensure layout system knows their sizes
  [MDCButtonInDialogMinimumSizeMutator mutate:self.noButton];
  [MDCButtonInDialogMinimumSizeMutator mutate:self.yesButton];
}

@end
```

**Comment by ianegordon** [comment] 2017-09-11 16:10
In general, I recommend MDCButton's behavior should match UIButton's.  Specifically, I recommend our initWithFrame: implementation matches Apple's.

**Comment by randallli** [comment] 2017-09-11 17:52
I think what @ianegordon is saying is that we should not ignore/override the frame passed in as an argument.

As for mutator structure that LGTM. We may iterate on the names.

**Comment by romoore** [comment] 2017-09-11 18:44
Ok, so we let clients that call with an explicit frame use that, but we change our default initializers to set a frame with  the correct minimum size?

**Comment by ajsecord** [comment] 2018-03-15 15:44
What is this blocked on now?

**Comment by ianegordon** [comment] 2018-03-15 17:40
@romoore Can you proceed?

**Comment by zakdances** [comment] 2018-07-12 21:51
This is still broken. It's especially noticeable when using storyboard. I have to attach an IBOutlet to every MDCButton/MDCRaisedButton so I can manually call sizeToFit(), otherwise they're all the wrong size.

**Comment by ultimate-deej** [comment] 2018-09-26 14:51
This must be due to the lack of `intrinsicContentSize`.

**Comment by jbarros35** [comment] 2018-10-11 16:07
how can we work on that?
Button touch target does not meet minimum size guidlines of (48, 48). Button: <MDCFloatingButton: 0x7fd855059200; baseClass = UIButton; frame = (0 0; 0 0); opaque = NO; layer = <MDCShapedShadowLayer: 0x600002a2cc80>>, Touch Target: {0, 0}

**Comment by jbarros35** [comment] 2019-03-06 14:20
Still happens

**Comment by romoore** [comment] 2019-08-08 01:47
It's unlikely that we will be changing the default size of these buttons, since that would be breaking for many clients. I believe it's reasonable for clients to set button bounds (or minimum size) and use `hitAreaInsets` for touch targets.  Closing this as "Works as Intended."

**Closed by romoore** 2019-08-08 01:47 UTC
Labels: [Buttons], risky:Visual change, type:Bug
