### ISSUE TITLE
[ShadowLayer] MDCShadowLayer doesn't animate properly

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4108] opened 2018-05-10 14:08 UTC
This is an internal issue. If you are a Googler, please visit [b/64615049](http://b/64615049) for more details.

---
#### Internal data
- Associated internal bug: [b/64615049](http://b/64615049)

**Comment by ianegordon** [comment] 2018-05-24 19:51
Duplicate of #1287

**Comment by material-mirror** [comment] 2019-02-11 20:52
The internal issue [b/64615049](http://b/64615049) is now closed. This issue is being closed as a result.

**Closed by material-mirror** 2019-02-11 20:52 UTC
Labels: [ShadowLayer], type:Bug
