### ISSUE TITLE
[FlexibleHeader] sectionHeadersPinToVisibleBounds doesn't work with MDCFlexibleHeaderViewController and UIViewController

### ISSUE THREAD

**Issue by haroldogtf** [material-components/material-components-ios#2076] opened 2017-10-02 17:19 UTC
### Overview
I have a MDCFlexibleHeaderViewController and a UIViewController in my app working perfectly.

But if I set `sectionHeadersPinToVisibleBounds` to `true` the header doesn't scroll together with FlexibleHeader.

![header](https://user-images.githubusercontent.com/1682169/31089970-5fb1f6ae-a77c-11e7-898d-66e3e0119fb9.gif)

### Reproduction steps:
`(self.myCollectionView.collectionViewLayout as! UICollectionViewFlowLayout).sectionHeadersPinToVisibleBounds = true`

### Version number
 - MaterialComponents/FlexibleHeader (34.0.2)

### Operating system and device
iOS 11 - iPhone 6s, 
iOS 11 - Simulator iPhone 8
iOS 11 - Simulator iPhone 8 Plus

**Comment by willlarche** [comment] 2017-10-02 17:22
Just wanna say, thank you for the great gif in your ticket! Someone will take a look at this soon.

**Comment by chuga** [comment] 2017-10-02 21:55
Hi Haroldo, could you do me a favor and try this again with commit 80d054e? If you're using cocoapods you should be able to do the following:
pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios', :commit => '80d054e'

Also, is this only happening on iOS 11?

**Comment by haroldogtf** [comment] 2017-10-03 17:08
Hi,

I tried with your commit, but the issue persists. I also tried in iOS 10.3.1 - Simulator iPhone 7 and 7 Plus but the HeaderSection was further separated.

I uploaded a sample **code** to make easy to reproduce (https://github.com/haroldogtf/FlexibleHeader-Issue2076)

**Comment by haroldogtf** [comment] 2017-10-05 12:38
Hi, any update?

**Comment by chuga** [comment] 2017-10-05 19:06
Hi Haroldo, thanks for uploading some sample code as that will make debugging this way easier for us.
We currently don't have any updates as we're all looking at other bugs at the moment. We do accept contributions though, so if you do end up figuring out what's broken before we do, please feel free to send us a PR.

**Comment by jverkoey** [comment] 2018-08-27 13:05
Duplicate of https://github.com/material-components/material-components-ios/issues/2032.

**Closed by jverkoey** 2018-08-27 13:05 UTC
Labels: [FlexibleHeader], type:Bug

**Comment by Peeoner174** [comment] 2018-12-19 10:43
I find temp solution. 
`extension ContactViewController: MDCFlexibleHeaderViewLayoutDelegate {
    
    public func flexibleHeaderViewController(_ flexibleHeaderViewController: MDCFlexibleHeaderViewController,
                                             flexibleHeaderViewFrameDidChange flexibleHeaderView: MDCFlexibleHeaderView) {
        if flexibleHeaderView.scrollPhasePercentage == 0 {
            self.tableView.beginUpdates()
        }
}`

**Comment by haroldogtf** [comment] 2018-12-19 11:55
I tried here, but I am using UICollectionView and it doesn't have beginUpdates.
Thank you @Peeoner174 for your effort.
