### ISSUE TITLE
Icons collisions possible 

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#2917] opened 2018-02-09 18:10 UTC
Icons we offer via MDCIcons may collide with  other icons:

internal bug: b/73132837

**Comment by romoore** [comment] 2018-02-09 18:15
Let's try to add a test to cover the possibility of a nil bundle coming back in [`[MDCIcon bundleNamed]`](https://github.com/material-components/material-components-ios/blob/develop/components/private/Icons/src/MDCIcons.m#L34)

**Comment by ianegordon** [comment] 2018-06-01 18:07
This is caused by icon de-duplication as part of our internal build process.
It is out of scope of MDC-iOS.

**Closed by ianegordon** 2018-06-01 18:07 UTC
Labels: Needs actionability review, [Icons], type:Bug
