### ISSUE TITLE
Input chips become editable when tapped in iOS, this discerption and Video provided 

### ISSUE THREAD

**Issue by anuragfluke** [material-components/material-components-ios#8763] opened 2019-11-10 07:22 UTC
Input chips become editable when tapped in iOS, this discerption and Video provided in https://material.io/components/chips/#input-chips

## Expected behavior

there should be some API for developer to do this task. I am not able to find out anything useful in iOS

## Actual behavior
unable to find anything which can give you same animation and editable 
[editvideoon google.mp4.zip](https://github.com/material-components/material-components-ios/files/3828169/editvideoon.google.mp4.zip)

feature

**Comment by romoore** [comment] 2019-11-12 14:12
Hi @anuragfluke, thanks for filing this Issue. Those examples in the Chips article show possibilities for Chips components. MDCChipView does not support inline editing as shown in the "Editable" section, nor does it directly support dialog presentation as shown in the "Expandable" section. If you need these behaviors, I suspect you will need to build them yourself.

For the Editable example, you might:
1.  Add target/action for the Chip that removes it from its container and pre-populate a text field with the text that was entered to generate the Chip.
2.  The user can then edit that text and after entering "Return" on the input keyboard, it converts back to a Chip.

I'm closing this issue because I believe MDCChipView is working as intended, and these guidelines are more appropriately built by App developers than built-in to the MDC-iOS library components.

**Closed by romoore** 2019-11-12 14:12 UTC
Labels: Needs actionability review
