### ISSUE TITLE
[Releases] Update scripts to include private component changes in CHANGELOG

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3972] opened 2018-05-10 02:51 UTC
### Overview
When private components change they can have visible effects in public components. Changes to private components should be included in the CHANGELOG release notes.

### Version number
54.3.0

---

https://github.com/material-components/material-components-ios/issues/3320

**Comment by ianegordon** [comment] 2018-08-23 23:30
Closed as a duplicate of #3320

**Closed by ianegordon** 2018-08-23 23:30 UTC
Labels: Needs actionability review
