### ISSUE TITLE
[Catalog] MDCNavigationBar examples overlap iPhone X cut-out

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1974] opened 2017-09-13 13:46 UTC
### Overview
The MDCNavigationBar Typical Use example (and most of the others) overlap the top cut-out on the iPhone X and make the title unreadable and the items (buttons) partially overlapped.

**Typical Use on iPhone X**
![mdcnavbar-typical-ipx](https://user-images.githubusercontent.com/1753199/30380722-48225ba6-98d5-11e7-8429-39a037d199d7.png)

**With Items on iPhone X**
![mdcnavbar-items-ipx](https://user-images.githubusercontent.com/1753199/30380730-4e941db2-98d5-11e7-9f8a-0cead10537a5.png)

### Reproduction steps
Launch MDC Catalog on iPhone X &rarr; Navigation Bar &rarr; Demo

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

**Comment by chuga** [comment] 2017-09-19 20:38
Marking as a duplicate of #2009

**Closed by chuga** 2017-09-19 20:38 UTC
Labels: device:iPhone X, type:Visual bug, where:Catalog
