### ISSUE TITLE
[Chips] MDCChipView flips layout of subclass' subviews

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3971] opened 2018-05-10 02:51 UTC
### Overview
In MDCChipView's layoutSubviews, it applies RTL layout by flipping all of its subviews:
https://github.com/material-components/material-components-ios/blob/f9b034955f1e7b3ed825150f14294cb1f9a97b91/components/Chips/src/MDCChipView.m#L614

Unfortunately this also flips any subviews that subclasses have added, which can cause unexpected layout behavior such as double-flipping.

### Reproduction steps
Subclass MDCChipView, add your own view and try to make it support RTL.

---

https://github.com/material-components/material-components-ios/issues/3307

**Comment by romoore** [comment] 2018-05-25 12:31
Duplicate of #3307

**Closed by romoore** 2018-05-25 12:31 UTC
Labels: Needs actionability review, [Chips], type:Bug
