### ISSUE TITLE
[ButtonBar] ButtonBar does not respect the Safe Area

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2285] opened 2017-10-26 10:47 UTC
### Overview
The button bar has a set of items which does not respect the Safe Area. And as the items are not individually accessible, it means the ButtonBar itself as to be adjusted to fit inside the Safe Area, and the shadow/background is not so nice.
The items should probably respect the safe area, allowing the button bar to spread outside of it.

### Reproduction steps
 - Add a ButtonBar taking the full width of the screen.
 - Open on iPhone X landscape.

### Version number
 - 38.0

### Operating system and device
 - iOS 11, iPhone X

**Comment by jverkoey** [comment] 2018-08-24 15:07
We're increasingly moving towards having the ButtonBar be a private implementation detail of the AppBar component, so I recommend using an App Bar instead.

That being said, the behavior described here is working as intended.

**Closed by jverkoey** 2018-08-24 15:07 UTC
Labels: Needs actionability review, type:Bug
